---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Admin.
--- DateTime: 05.06.2019 05:55
---


local AIO = AIO or require("AIO")

if AIO.AddAddon() then
    -- we are on server
    print("___________________GLOBALVARS")
    SpellLevelTable ={

        Arms = {
            1,	--BattleStance
            1,		--Heroic Strike
            --4, 	--Charge
            4,	--Rend
            6,	--Thunder Clap
            8,	--HarmString
            12,	--Overpower
            16,	--Mocking Blow
            20,	--Retaliation
            71,	--Shattering throw
            61,	--heroic Throw
        },
        Furor = {

            1,	--Battlesout
            6,	--Victory Rush
            --14,	--Demo Shout
            20,	--Cleave
            --22,	--Intimidating Shout
            24, 	--Execute
            26,	--ChallengingShout
            30,	--BeserkerStance
            30,	--Death Wish
            30,	--Intercept
            30,	--Slam
            32,	--Beserker rage
            36,	--Whirlwind
            --38,	--Pummel
            50,	--Recklessness
            54,	--Commanding shout
            75,	--Enraged Regeneration
        },
        Protection = {
            10, 	--Bloodrage
            10,	--Sunder Armor
            10,	--Taunt
            12,		--Shield Bash
            14,	--Revenge
            16,	--Shield Block
            18,	--Disarm
            20,	--Stance Mastery
            28,	--ShieldWall
            40,	--Shield Slam
            64,	--Spell reflect
            70,	--Intervene
        },

        Arcane = {
            1,	--Arcane Intellect
            4,	--Conjure Water
            6,	--Conjure Food
            8,	--Arcane Missles
            --8,	--Polymorph
            10,	--Dampen Magic
            12,	--Slow Fall
            14,	--Arcane Explosion
            18,	--Amplify Magic
            18,	--Remove Curse
            --20,	--Blink
            20,	--Evocation
            20,	--ManaShield
            --24,	--CounterSpell
            28,	--Conjure Mana Gem
            34,	--Mage Armor
            64,	--Arcane Blast
            68,		--Invisibility
            70,	--Ritual of Refreshment
            70,	--Spellsteal
            78,	--Mirror Image
        },
        Fire = {
            1,	--Fireball
            6,	--Fire Blast
            16,	--FlameStrike
            20,	--Fire Ward
            22,	--Scorch
            66,	--Molten Armor
            72,	--Frostfire Bolt
        },
        FrostMage = {
            4,	--FrostBolt
            10,	--Frost Nova
            20,		--Blizzard
            22,	--Frost Ward
            26,	--Cone of Cold
            --30,	--Ice Armor
            --30,	--Ice Block
            66,	--Ice Lance
        },

        Assasination = {
            1,	--Eviscerate
            10,	--Slice and Dice
            14,	--Expose Armor
            --	14,	--Garrote
            --	18,	--Ambush
            20,	--Dismantle
            20,	--Rupture
            --	26,	--Cheap shot
            30,	--Kidney Shot
            66,	--Evenom
            66,	--Deadly Throw
        },
        Combat = {
            1,	--Sinister Strike
            1,		--BackStab
            6,	--Gouge
            --	8,	--Evasion
            10,	--Sprint
            --	12,	--Kick
            16,	--Feint
            66,	--Shiv
            66,	--Fan of Knives
        },
        Subletly = {
            --	1,	--Stealth
            --	4,	--Pick Pocket
            --	10,	--Sap
            20,	--Ghostly Strike
            22,	--Distract
            22,	--Vanish
            24,	--Detect Traps
            30,	--Disarm Trap
            --	34,	--Blind
            40,	--Safe Fall
            66,	--Cloak of Shadows
            66,	--Tricks of the Trade
        },


        Balance = {
            1, --Wrath
            4, --Moonfire
            6, --Thorns
            --	8, --Entangliing Roots
            10, --Natures Grasp
            18, --Faerie Fire
            18, --Hibernate
            20, --Starfire
            22,  --Soothe Animal
            40, --Hurricane
            --	40, --Innervate
            --	44,  --Barkskin
            70 --Cyclone
        },
        Feral = {
            10,      --BearForm
            10,		--Demo Roar
            10,     --Growl
            10,     --maul
            12,	    --Enrage
            14, --Bash
            --	16,	--Aquatic Form
            16,	--Swipe[Bear]
            --	16,	--Travel Form
            16,	--Faeri Fire Feral
            20,	--Cat Form
            20,	--Claw
            --	20,	--Prowl
            20,	--Rip
            22,	--Shred
            24,	--Rake
            24,	--Tigers Fury
            26,	--Dash
            28,	--Challenging Roar
            28,	--Cower
            32,	--Ferocious Bite
            32,	--Ravage
            --	32,	--Track Humanoids
            36,	--Frenzied Regeneration
            36,	--Pounce
            40,	--Faelin Grace
            40,	--Savage Defense
            --	61,	--Flight Form
            62,	--Maim
            66,	--Lacerate
            77,	--Swipe Cat
        },
        Restoration = {
            1, 	--Healing Touch
            1,	--Mark of the Wild
            4,	--Rejuvenation
            12,	--Regrowth
            12,	--Revive
            --	20,	--Rebirth
            24,	--Remove Curse
            26,	--Abolish Poison
            30,	--Tranqility
            50,	--Gift of the Wild
            64,	--Lifebloom
            80,	--Nourish
        },

        BeastMaster = {
            --	4,	--Aspect of the Monkey
            10,	--Aspect of the Hawk
            --	10,	--Call PET
            --	10,	--Dismiss PET
            --	10,	--Feed PET
            --	10,	--Revive PET
            --	10,	--Tame Beast
            --	12,	--Mend PET
            --	14,	--Eagle Eye
            --	14,	--Eye of the Beast
            14,	--Scare Beast
            --	16,	--Aspect of the Cheetah
            18,	--Aspect of the Vipper
            24,	--Beast Lore
            30,	--Aspect of the Beast
            --	40,	--Aspect of the Pack
            46,	--Aspect of the Wild
            66,	--Kill Command
            66,	--Aspect of the Dragonhawk
            66,	--Masters Call
            --	66,	--Call Stabled Pet

        },
        Marksman = {
            1,  --AutoShot
            4,	--[Serpent Sting]
            6,	--[Arcane Shot]
            --	6,	--[Hunter's Mark]
            8,	--[Concussive Shot]
            12,	--[Distracting Shot]
            18,	--[Multi-Shot]
            22,	--[Scorpid Sting]
            26,	--[Rapid Fire]
            --	32,	--[Flare]
            36,	--[Viper Sting]
            40,	--[Volley]
            50,	--[Steady Shot]
            60,	--[Tranquilizing Shot]
            71,	--[Kill Shot]
        },
        Survival = {
            1,  --RaptorStrike
            --	1,	--Track Beasts]
            --	10,	--Track Humanoids]
            12,	--Wing Clip]
            1,	--Immolation Trap]
            16,	--Mongoose Bite]
            --	18,	--Track Undead]
            20	,	--Disengage]
            20,	--Freezing Trap]
            --	24,	--Track Hidden]
            --	26,	--Track Elementals]
            28,	--Frost Trap]
            30,	--Feign Death]
            --	32,	--Track Demons]
            34,	--Explosive Trap]
            --	40,	--Track Giants]
            --	50,	--Track Dragonkin]
            60,	--Deterrence]
            66,	--Snake Trap
            66,	--Misdirection]
            66,	--Freezing Arrow]
        },

        Elemental = {

            1,	--Lightning Bolt
            4,	--Earth Shock
            --	6,	--Earthbind Totem
            8,	--Stoneclaw Totem
            10,	--Fame Shock
            10,	--Searing Totem
            12,	--Fire Nova
            --	12,	--Purge
            --	16,	--Wind Shear
            --	20,	--Frost Shock
            26,	--Magma Totem
            30,	--Call of the Elements
            32, 	--Chain Lightning
            30,	--Call of the Ancestors
            30,	--Call of the Spirits
            68,	--Fire Ele Totem
            68,	--Lava Burst
            68,	--Hex

        },
        Enhancement = {
            1, 	--Rockbiter
            4,	--StoneSkin Totem
            8,	--Lightning Shield
            10,	--Flametongue Wpn
            10,	--Strenght of Earth Totem
            16,	--Ghost Wolf
            20,	--Frostbrand Wpn
            22,	--Water Breathing
            24,	--Frost Resistance totem
            --	26,	--Far Sight
            28,	--Fire Resistance Totem
            28,	--Flametongue Totem
            28,	--Water Walking
            30,	--Astral Recall
            --	30,	--Grounding Totem
            30,	--Nature Resi Totem
            --	30,	--Windfury Wpn
            32,	--Windfury Totem
            34,	--Sentry Totem
            64,	--Wrath of the Air Totem
            66,	--Earth Ele Totem
            66,	--Bloodlust
            67,	--Heroism
        },
        ShamanResto= {
            1,	--Healing Wave
            12,	--Ancestral Spirit
            16,	--Cure Toxins
            18,	--Tremor Totem
            20,	--Healing Stream Totem
            20,	--Lesser Healing Wave
            20,	--Water Shield
            --	26,	--Mana Spring Totem
            30,	--Earthliving Wpn
            --	30,	--Reincarnation
            30,	--Totemic Recall
            --	40, 	--Cleansing Totem
            40,	--Chain Heal

        },

        Disci = {
            1,	--Power Word Fort
            6,		--PowerWord Shield
            --	12,	--Inner Fire
            --	18,	--Dispel Magic
            --	20,	--Fear Ward
            20,	--Shacke Undead
            24,	--Mana Burn
            30,	--Divine Spirit
            34,	--Levitate,
            70,	--Mass Dispel

        },
        PriestHoly = {
            8,	--Renew
            10,	--Ressurection
            14,	--Cure Disease
            16,	--Heal
            20,	--Flash Heal
            20,	--Holy Fire
            --	20,	--Holy Nova
            30,	--Prayer of Healing
            32,	--Abolish Disease
            40,	--Greater Heal
            64,	--Binding Heal
            68,	--Prayer of Mending
            70,	--Divine Hymn
            70,	--Hymn of Hope
        },
        Shadow = {
            4, 	--Shadow Word Pain
            8,	--Fade
            10,	--Mind Blast
            --	14,	--Psychic Scream
            20,	--Devo Plague
            20,	--Mind Soothe
            22,	--Mind Vision
            30,	--Mind Control
            30,	--ShadowProtection
            62,	--Shadow word Death
            66,	--Shadowfiend
            72,	--Mind Sear
        },

        Affliction = {
            4,	--Corruption
            4,	--Curse of Weakness
            --	6,	--Life Tap
            --	8,	--Curse of Agony
            --	8,	--Fear
            14,	--Drain Soul
            14,	--Drain Life
            24,	--Drain Mana
            26,	--Curse of Tongues
            --	32,	--Curse of the Elements
            40,	--Howl of Terror
            --	42,	--Death Coil
            60,	--Curse of Doom
            70,	--Seed of Corruption
        },
        Demonology = {
            --	1,	--Demon Skin
            --	1,	--Summon Imp
            10, 	--Create Healthstone
            12,	    --Health Funnel
            16,	--Unending Breath
            18,	--Create Soulstone
            22,	--Eye of Kilrogg
            24,	--Sense Demons
            26,	--Detect invis
            --	28,	--Banish
            28,	--Create Firestone
            30,	--Enslave Demon
            32,	--Shadow Ward
            36,	--Create SpellStone
            62,	--Fel Armor
            66,	--Soulshatter
            68,	--Ritual of Soulshatter
            80,	--Demonic Circle Summon
            80,	--Demonic Circle Teleport
        },
        Destruction= {
            1,	--Shadow Bolt
            1,	--Immolate
            18,	--Searing Pain
            20,	--Rain of Fire
            30,	--Hellfire
            48,	--Soul Fire
            64,	--Incinerate
            75,	--Shadowflame
        },

        PalaHoly = {
            1, 	--Holy Light
            1,	--Seal of Righteousness
            8,	--Purify
            10,	--Lay on Hands
            12,	--Redemption
            14,	--Blessing of Wisdom
            20,	--Consecration
            20,	--Exorcism
            20,	--Flash of Light
            --	20,	--Sense Undead
            22,	--Concentration Aura
            24,	--Turn Evil
            30,	--Seal of Light
            14,	--Seal of Wisdom
            --	42,	--Cleanse
            50,	--Holy Wrath
            66,	--Divine Plea
            78,	--Sacred Shield
        },
        PalaProt = {
            1,	--Devotionaura
            6,	--Divine Protection
            8,	--Hammer of Justice
            --	19,	--Hand of Protection
            14,	--Righteous Defense
            --	16,	--Hand of Reckoning
            16,	--Righteous Fury
            --	18,	--Hand of Freedom
            --	20,	--Blessing of Kings
            --	22,	--Seal of Justice
            26,	--Hand of Salvation
            28,	--Shadow Resi Aura
            30,	--Divine Intervention
            32,	--Frost Resi Aura
            --	34,	--Divine Shield
            36,	--Fire Resi Aura
            46,	--Hand of Sacrifice
            75,	--Shield of Righteousness
        },
        Retri = {
            4,	--Blessing of Might
            4,	--Judgement of Light
            12,	--Jugment of Wisdom
            16,	--Retribution Aura
            28,	--Judgement of Justice
            44,	--Hammer of Wrath
            62,	--CrusaderAura
            64,	--Seal of Vengeance
            64,	--Seal of corruption
            70,	--Avenging Wrath
        },

    }
    SpellTable = {
        Arms = {
            2457,	--BattleStance
            78,		--Heroic Strike
            --100, 	--Charge
            772,	--Rend
            6343,	--Thunder Clap
            --1715,	--HarmString
            7384,	--Overpower
            694,	--Mocking Blow
            20230,	--Retaliation
            64382,	--Shattering throw
            57755,	--Heroic Throw
        },
        Furor = {

            6673,	--Battlesout
            34428,	--Victory Rush
            --1160,	--Demo Shout
            845,	--Cleave
            --5246,	--Intimidating Shout
            5308, 	--Execute
            1161,	--ChallengingShout
            2458,	--BeserkerStance
            12292,	--Death Wish
            20252,	--Intercept
            1464,	--Slam
            18499,	--Beserker rage
            1680,	--Whirlwind
            --6552,	--Pummel
            1719,	--Recklessness
            469,	--Commanding shout
            55694,	--Enraged Regeneration
        },
        Protection = {
            2687, 	--Bloodrage
            7386,	--Sunder Armor
            355,	--Taunt
            72,		--Shield Bash
            6572,	--Revenge
            2565,	--Shield Block
            676,	--Disarm
            12678,	--Stance Mastery
            871,	--ShieldWall
            23922,	--Shield Slam
            23920,	--Spell reflect
            3411,	--Intervene
        },

        Arcane = {
            1459,	--Arcane Intellect
            5504,	--Conjure Water
            587,	--Conjure Food
            5143,	--Arcane Missles
            --118,	--Polymorph
            604,	--Dampen Magic
            130,	--Slow Fall
            1449,	--Arcane Explosion
            1008,	--Amplify Magic
            475,	--Remove Curse
            --1953,	--Blink
            12051,	--Evocation
            1463,	--ManaShield
            --2139,	--CounterSpell
            759,	--Conjure Mana Gem
            6117,	--Mage Armor
            30451,	--Arcane Blast
            66,		--Invisibility
            43987,	--Ritual of Refreshment
            30449,	--Spellsteal
            55342,	--Mirror Image
        },
        Fire = {
            133,	--Fireball
            2136,	--Fire Blast
            2120,	--FlameStrike
            543,	--Fire Ward
            2948,	--Scorch
            30482,	--Molten Armor
            44614,	--Frostfire Bolt
        },
        FrostMage = {
            116,	--FrostBolt
            --122,	--Frost Nova
            10,		--Blizzard
            6143,	--Frost Ward
            120,	--Cone of Cold
            --7302,	--Ice Armor
            --45438,	--Ice Block
            30455,	--Ice Lance
        },


        Assasination = {
            2098,	--Eviscerate
            5171,	--Slice and Dice
            8647,	--Expose Armor
            --	703,	--Garrote
            --	8676,	--Ambush
            51722,	--Dismantle
            1943,	--Rupture
            --	1833,	--Cheap shot
            408,	--Kidney Shot
            --	32645,	--Evenom
            26679,	--Deadly Throw
        },
        Combat = {
            1752,	--Sinister Strike
            53,		--BackStab
            1776,	--Gouge
            --	5277,	--Evasion
            2983,	--Sprint
            --	1766,	--Kick
            1966,	--Feint
            5938,	--Shiv
            51723,	--Fan of Knives
        },
        Subletly = {
            --	1784,	--Stealth
            --	921,	--Pick Pocket
            --	6770,	--Sap
            14278,	--Ghostly Strike
            1725,	--Distract
            1856,	--Vanish
            2836,	--Detect Traps
            1842,	--Disarm Trap
            --	2094,	--Blind
            1860,	--Safe Fall
            31224,	--Cloak of Shadows
            57934,	--Tricks of the Trade
        },

        Balance = {
            5176,	--Wrath
            8921,	--Moonfire
            467,	--Thorns
            --	339, 	--Entangliing Roots
            16689,	--Natures Grasp
            770,	--Faerie Fire
            2637, 	--Hibernate
            2912,	--Starfire
            2908,	--Soothe Animal
            16914,	--Hurricane
            --	29166,	--Innervate
            --	22812,	--Barkskin
            33786,	--Cyclone
        },
        Feral = {
            5487,   --BearForm
            99,		--Demo Roar
            6795,   --growl
            6807,   --Maul
            5229,	--Enrage
            5211, 	--Bash
            --	1066,	--Aquatic Form
            779,	--Swipe[Bear]
            --	783,	--Travel Form
            16857,	--Faeri Fire Feral
            768,	--Cat Form
            1082,	--Claw
            --	5215,	--Prowl
            1079,	--Rip
            5221,	--Shred
            1822,	--Rake
            5217,	--Tigers Fury
            1850,	--Dash
            5209,	--Challenging Roar
            8998,	--Cower
            22568,	--Ferocious Bite
            6785,	--Ravage
            --	5225,	--Track Humanoids
            22842,	--Frenzied Regeneration
            9005,	--Pounce
            20719,	--Faelin Grace
            62600,	--Savage Defense
            --	33943,	--Flight Form
            22570,	--Maim
            33745,	--Lacerate
            62078,	--Swipe Cat
        },
        Restoration = {
            5185, 	--Healing Touch
            1126,	--Mark of the Wild
            774,	--Rejuvenation
            8936,	--Regrowth
            50769,	--Revive
            --	20484,	--Rebirth
            2782,	--Remove Curse
            2893,	--Abolish Poison
            740,	--Tranqility
            21849,	--Gift of the Wild
            33763,	--Lifebloom
            50464,	--Nourish
        },

        BeastMaster = {
            --	13163,	--Aspect of the Monkey
            13165,	--Aspect of the Hawk
            --	883,	--Call PET
            --	2641,	--Dismiss PET
            --	6991,	--Feed PET
            --	982,	--Revive PET
            --	1515,	--Tame Beast
            --	136,	--Mend PET
            --	6197,	--Eagle Eye
            --	1002,	--Eye of the Beast
            --	1513,	--Scare Beast
            --	5118,	--Aspect of the Cheetah
            34074,	--Aspect of the Vipper
            1462,	--Beast Lore
            13161,	--Aspect of the Beast
            --	13159,	--Aspect of the Pack
            20043,	--Aspect of the Wild
            34026,	--Kill Command
            61846,	--Aspect of the Dragonhawk
            53271,	--Masters Call
            --	62757,	--Call Stabled Pet

        },
        Marksman = {
            75,     --AutoShot
            1978,	--[Serpent Sting]
            3044,	--[Arcane Shot]
            --	1130,	--[Hunter's Mark]
            5116,	--[Concussive Shot]
            20736,	--[Distracting Shot]
            2643,	--[Multi-Shot]
            3043,	--[Scorpid Sting]
            3045,	--[Rapid Fire]
            --	1543,	--[Flare]
            3034,	--[Viper Sting]
            1510,	--[Volley]
            56641,	--[Steady Shot]
            19801,	--[Tranquilizing Shot]
            53351,	--[Kill Shot]
        },
        Survival = {
            2973,   --Raptor strike
            --	1494,	--Track Beasts]
            --	19883,	--Track Humanoids]
            2974,	--Wing Clip]
            13795,	--Immolation Trap]
            1495,	--Mongoose Bite]
            --	19884,	--Track Undead]
            781	,	--Disengage]
            1499,	--Freezing Trap]
            --	19885,	--Track Hidden]
            --	19880,	--Track Elementals]
            13809,	--Frost Trap]
            5384,	--Feign Death]
            --	19878,	--Track Demons]
            13813,	--Explosive Trap]
            --	19882,	--Track Giants]
            --	19879,	--Track Dragonkin]
            19263,	--Deterrence]
            34600,	--Snake Trap
            34477,	--Misdirection]
            60192,	--Freezing Arrow]
        },

        Elemental = {

            403,	--Lightning Bolt
            8042,	--Earth Shock
            --	2484,	--Earthbind Totem
            5730,	--Stoneclaw Totem
            8050,	--Fame Shock
            3599,	--Searing Totem
            1535,	--Fire Nova
            --	370,	--Purge
            --	57994,	--Wind Shear
            --	8056,	--Frost Shock
            8190,	--Magma Totem
            66842,	--Call of the Elements
            421, 	--Chain Lightning
            66843,	--Call of the Ancestors
            66844,	--Call of the Spirits
            2894,	--Fire Ele Totem
            51505,	--Lava Burst
            51514,	--Hex

        },
        Enhancement = {
            8017, 	--Rockbiter
            8071,	--StoneSkin Totem
            324,	--Lightning Shield
            8024,	--Flametongue Wpn
            8075,	--Strenght of Earth Totem
            2645,	--Ghost Wolf
            8033,	--Frostbrand Wpn
            131,	--Water Breathing
            8181,	--Frost Resistance totem
            --	6196,	--Far Sight
            8184,	--Fire Resistance Totem
            8227,	--Flametongue Totem
            546,	--Water Walking
            556,	--Astral Recall
            --	8177,	--Grounding Totem
            10595,	--Nature Resi Totem
            --	8242,	--Windfury Wpn
            8512,	--Windfury Totem
            6495,	--Sentry Totem
            3738,	--Wrath of the Air Totem
            2062,	--Earth Ele Totem
            2825,	--Bloodlust
            32182,	--Heroism
        },
        ShamanResto= {
            331,	--Healing Wave
            2008,	--Ancestral Spirit
            526,	--Cure Toxins
            8134,	--Tremor Totem
            5394,	--Healing Stream Totem
            8004,	--Lesser Healing Wave
            52127,	--Water Shield
            --	5675,	--Mana Spring Totem
            51730,	--Earthliving Wpn
            --	20608,	--Reincarnation
            36936,	--Totemic Recall
            --	8170, 	--Cleansing Totem
            1064,	--Chain Heal

        },

        Disci = {
            1243,	--Power Word Fort
            17,		--PowerWord Shield
            --	588,	--Inner Fire
            --	527,	--Dispel Magic
            --	6346,	--Fear Ward
            9484,	--Shacke Undead
            8129,	--Mana Burn
            14752,	--Divine Spirit
            1706,	--Levitate,
            32375,	--Mass Dispel

        },
        PriestHoly = {
            139,	--Renew
            2006,	--Ressurection
            528,	--Cure Disease
            2054,	--Heal
            2061,	--Flash Heal
            --	14914,	--Holy Fire
            15237,	--Holy Nova
            596,	--Prayer of Healing
            552,	--Abolish Disease
            2060,	--Greater Heal
            32546,	--Binding Heal
            33076,	--Prayer of Mending
            64843,	--Divine Hymn
            64901,	--Hymn of Hope
        },
        Shadow = {
            589, 	--Shadow Word Pain
            586,	--Fade
            8092,	--Mind Blast
            --	8122,	--Psychic Scream
            2944,	--Devo Plague
            453,	--Mind Soothe
            2096,	--Mind Vision
            605,	--Mind Control
            976,	--ShadowProtection
            32379,	--Shadow word Death
            34433,	--Shadowfiend
            48045,	--Mind Sear
        },

        Affliction = {
            172,	--Corruption
            702,	--Curse of Weakness
            --	1454,	--Life Tap
            --	980,	--Curse of Agony
            --	5782,	--Fear
            1120,	--Drain Soul
            689,	--Drain Life
            5138,	--Drain Mana
            1714,	--Curse of Tongues
            --	1490,	--Curse of the Elements
            5484,	--Howl of Terror
            --	6789,	--Death Coil
            603,	--Curse of Doom
            27243,	--Seed of Corruption
        },
        Demonology = {
            --	687,	--Demon Skin
            --	688,	--Summon Imp
            6201, 	--Create Healthstone
            755,	--Health Funnel
            5697,	--Unending Breath
            693,	--Create Soulstone
            698,	--Eye of Kilrogg
            5500,	--Sense Demons
            132,	--Detect invis
            --	710,	--Banish
            6366,	--Create Firestone
            1098,	--Enslave Demon
            6229,	--Shadow Ward
            2362,	--Create SpellStone
            28176,	--Fel Armor
            29858,	--Soulshatter
            29893,	--Ritual of Soulshatter
            48018,	--Demonic Circle Summon
            48020,	--Demonic Circle Teleport
            -- 1122 --inderno
        },
        Destruction= {
            686,	--Shadow Bolt
            348,	--Immolate
            5676,	--Searing Pain
            5740,	--Rain of Fire
            1949,	--Hellfire
            6353,	--Soul Fire
            29722,	--Incinerate
            47897,	--Shadowflame
        },

        PalaHoly = {
            635, 	--Holy Light
            21084,	--Seal of Righteousness
            1152,	--Purify
            633,	--Lay on Hands
            7328,	--Redemption
            19742,	--Blessing of Wisdom
            26573,	--Consecration
            879,	--Exorcism
            19750,	--Flash of Light
            --	5502,	--Sense Undead
            19746,	--Concentration Aura
            10326,	--Turn Evil
            20165,	--Seal of Light
            19742,	--Seal of Wisdom
            --	4987,	--Cleanse
            2812,	--Holy Wrath
            54428,	--Divine Plea
            53601,	--Sacred Shield
        },
        PalaProt = {
            465,	--Devotionaura
            498,	--Divine Protection
            853,	--Hammer of Justice
            --	1022,	--Hand of Protection
            31789,	--Righteous Defense
            --	62124,	--Hand of Reckoning
            25780,	--Righteous Fury
            --	1044,	--Hand of Freedom
            --	20217,	--Blessing of Kings
            --	20164,	--Seal of Justice
            1038,	--Hand of Salvation
            19876,	--Shadow Resi Aura
            19752,	--Divine Intervention
            19888,	--Frost Resi Aura
            --	642,	--Divine Shield
            19891,	--Fire Resi Aura
            6940,	--Hand of Sacrifice
            53600,	--Shield of Righteousness
        },
        Retri = {
            19740,	--Blessing of Might
            20271,	--Judgement of Light
            53408,	--Jugment of Wisdom
            7294,	--Retribution Aura
            53407,	--Judgement of Justice
            24275,	--Hammer of Wrath
            32223,	--CrusaderAura
            32801,	--Seal of Vengeance
            53736,	--Seal of corruption
            31884,	--Avenging Wrath
        },

    }
    TalentSpecTable ={
        "Arms",
        "Furor",
        "Protection",
        "Arcane",
        "Fire",
        "FrostMage",
        "Assasination",
        "Combat",
        "Subletly",
        "Balance",
        "Feral",
        "Restoration",
        "BeastMaster",
        "Marksman",
        "Survival",
        "Elemental",
        "Enhancement",
        "ShamanResto",
        "Disci",
        "PriestHoly",
        "Shadow",
        "Affliction",
        "Demonology",
        "Destruction",
        "PalaHoly",
        "PalaProt",
        "Retri"

    }
    SpellRacials = {
        Active = {
            59752, -- Every Man for himself (human)
            59542, --[Gift of the Naaru] AP and SP Dreanei
            7744,  --[Will of the Forsaken] Undead
            20549, --[War Stomp]
            20572, --[Blood Fury] AP
            33702, --[Blood Fury] SP
            20577, --[Cannibalize]
            20589, --[Escape Artist]
            20594, --[Stoneform]
            25046, --[Arcane Torrent] ENERGY
            26297, --[Berserking] Troll
            28730, --[Arcane Torrent] MANA
            58984, --[Shadowmeld]
        },
        Passive ={
            -- 822,    --[Magic Resistance] bloodelf
            5227,   --[Underwater Breathing]
            6562,   --[Heroic Presence]
            20550,  --[Endurance]
            20551,  --[Nature Resistance]
            20579,  --[Shadow Resistance]
            20592,  --[Arcane Resistance]
            20596,  --[Frost Resistance]
            20555,  --[Regeneration]
            20557,  --[Beast Slaying]
            20573,  --[Hardiness]
            20574,  --[Axe Specialization]
            21563,  --Command
            20591,  --[Expansive Mind]
            20598,  --[The Human Spirit]
            20595,  --[Gun Specialization]
            20597,  --[Sword Specialization]
            20599,  --[Diplomacy]
            20864,  --[Mace Specialization]
            21009,  --[Elusiveness]
            58943,  --[Da Voodoo Shuffle]
            58985,  --[Perception]

        }

    }
    EXSpellLevelTable ={
        Warrior = {

            4, 	--Charge
            8,	--HamString
            14,	--Demo Shout (Not on exclusive list)
            22,	--Intimidating Shout
            32,	--Beserker rage (on the exclusive list)
            38,	--Pummel

        },
        Mage = {
            2,  --Frost Nova
            8,	--Polymorph
            20,	--Blink
            24,	--CounterSpell
            30,	--Ice Armor
            30,	--Ice Block
        },
        Rogue = {
            2,	--Stealth
            4,	--Pick Pocket
            8,	--Evasion
            10,	--Sap
            12,	--Kick
            14,	--Garrote
            18,	--Ambush
            26,	--Cheap shot
            34,	--Blind
            66, -- Evenom
        },
        Druid = {
            8, --Entangliing Roots
            16,	--Aquatic Form
            16,	--Travel Form
            20,	--Prowl
            20,	--Rebirth
            32,	--Track Humanoids
            40, --Innervate
            44,  --Barkskin
            61,	--Flight Form
        },
        Hunter = {
            1,	--Track Beasts]
            4,	--Aspect of the Monkey
            6,	--[Hunter's Mark]
            10,	--Track Humanoids]
            10,	--Call PET
            10,	--Dismiss PET
            10,	--Feed PET
            10,	--Revive PET
            10,	--Tame Beast
            12,	--Mend PET
            14,	--Eagle Eye
            14,	--Eye of the Beast
            14, --Scare Beast
            16,	--Aspect of the Cheetah
            18,	--Track Undead]
            24,	--Track Hidden]
            26,	--Track Elementals]
            32,	--Track Demons]
            32,	--[Flare]
            40,	--Track Giants]
            40,	--Aspect of the Pack
            50,	--Track Dragonkin]
            66,	--Call Stabled Pet
        },
        Shaman = {
            6,	--Earthbind Totem
            12,	--Purge
            16,	--Wind Shear
            20,	--Frost Shock
            26,	--Far Sight
            26,	--Mana Spring Totem
            30,	--Grounding Totem
            30,	--Windfury Wpn
            30,	--Reincarnation
            40, --Cleansing Totem
        },
        Priest = {

            12,	--Inner Fire
            14,	--Psychic Scream
            18,	--Dispel Magic
            20,	--Fear Ward
            20,	--Holy Nova
        },
        Warlock = {
            1,	--Demon Skin
            1,	--Summon Imp
            6,	--Life Tap
            8,	--Curse of Agony
            8,	--Fear
            28,	--Banish
            32,	--Curse of the Elements
            42,	--Death Coil
            50
        },
        Paladin = {

            16,	--Hand of Reckoning
            18,	--Hand of Freedom
            19,	--Hand of Protection
            20,	--Sense Undead

            20,	--Blessing of Kings
            22,	--Seal of Justice
            34,	--Divine Shield
            42,	--Cleanse

        },
    }
    EXSpellTable = {
        Warrior = {
            100, 	--Charge
            1715,	--HarmString
            1160,	--Demo Shout
            5246,	--Intimidating Shout
            6552,	--Pummel
        },
        Mage = {
            122,	--Frost Nova
            118,	--Polymorph
            1953,	--Blink
            2139,	--CounterSpell
            7302,	--Ice Armor
            45438,	--Ice Block

        },
        Rogue = {
            1784,	--Stealth
            921,	--Pick Pocket
            5277,	--Evasion
            6770,	--Sap
            1766,	--Kick
            703,	--Garrote
            8676,	--Ambush
            1833,	--Cheap shot
            2094,	--Blind
            32645,	--Evenom

        },
        Druid = {

            339, 	--Entangliing Roots
            1066,	--Aquatic Form
            783,	--Travel Form
            5215,	--Prowl
            20484,	--Rebirth
            5225,	--Track Humanoids
            29166,	--Innervate
            22812,	--Barkskin
            33943,	--Flight Form

        },
        Hunter = {
            1494,	--Track Beasts]
            13163,	--Aspect of the Monkey
            1130,	--[Hunter's Mark]
            19883,	--Track Humanoids]
            883,	--Call PET
            2641,	--Dismiss PET
            6991,	--Feed PET
            982,	--Revive PET
            1515,	--Tame Beast
            136,	--Mend PET
            6197,	--Eagle Eye
            1002,	--Eye of the Beast
            1513,	--Scare Beast
            5118,	--Aspect of the Cheetah
            19884,	--Track Undead]
            19885,	--Track Hidden]
            19880,	--Track Elementals]
            19878,	--Track Demons]
            1543,	--[Flare]
            19882,	--Track Giants]
            13159,	--Aspect of the Pack
            19879,	--Track Dragonkin]
            62757,	--Call Stabled Pet

        },
        Shaman = {
            2484,	--Earthbind Totem
            370,	--Purge
            57994,	--Wind Shear
            8056,	--Frost Shock
            6196,	--Far Sight
            5675,	--Mana Spring Totem
            8177,	--Grounding Totem
            8242,	--Windfury Wpn
            20608,	--Reincarnation
            8170, 	--Cleansing Totem
        },
        Priest = {
            588,	--Inner Fire
            8122,	--Psychic Scream
            527,	--Dispel Magic
            6346,	--Fear Ward
            14914,	--Holy Fire
        },
        Warlock = {
            687,	--Demon Skin
            688,	--Summon Imp
            1454,	--Life Tap
            980,	--Curse of Agony
            5782,	--Fear
            710,	--Banish
            1490,	--Curse of the Elements
            6789,	--Death Coil
            1122    --Inferno

        },
        Paladin = {
            62124,	--Hand of Reckoning
            1044,	--Hand of Freedom
            1022,	--Hand of Protection
            5502,	--Sense Undead
            20217,	--Blessing of Kings
            20164,	--Seal of Justice
            642,	--Divine Shield
            4987,	--Cleanse
        },

    }

    local T1_table = {
        ["13262"] = 110002,
        ["17068"] = 110004,
        ["17075"] = 110005,
        ["17076"] = 110006,
        ["17104"] = 110007,
        ["17182"] = 110008,
        ["18816"] = 110013,
        ["19019"] = 110040,
        ["19334"] = 110041,
        ["19335"] = 110042,
        ["19346"] = 110043,
        ["19347"] = 110044,
        ["19350"] = 110045,
        ["19351"] = 110046,
        ["19352"] = 110047,
        ["19353"] = 110048,
        ["19355"] = 110049,
        ["19356"] = 110050,
        ["19357"] = 110051,
        ["19360"] = 110052,
        ["19361"] = 110053,
        ["19363"] = 110054,
        ["19364"] = 110055,
        ["19365"] = 110056,
        ["19367"] = 110057,
        ["19368"] = 110058,
        ["20487"] = 110059,
        ["21126"] = 110061,
        ["21128"] = 110062,
        ["21134"] = 110063,
        ["21242"] = 110064,
        ["21244"] = 110065,
        ["21268"] = 110066,
        ["21272"] = 110067,
        ["21273"] = 110068,
        ["21275"] = 110069,
        ["21452"] = 110070,
        ["21459"] = 110071,
        ["21520"] = 110072,
        ["21521"] = 110073,
        ["21522"] = 110074,
        ["21523"] = 110075,
        ["21603"] = 110076,
        ["21616"] = 110077,
        ["21622"] = 110078,
        ["21635"] = 110079,
        ["21650"] = 110080,
        ["21673"] = 110081,
        ["21679"] = 110082,
        ["21703"] = 110083,
        ["21715"] = 110084,
        ["21839"] = 110085,
        ["22589"] = 110086,
        ["22630"] = 110087,
        ["22631"] = 110088,
        ["22632"] = 110089,
        ["22691"] = 110090,
        ["22798"] = 110092,
        ["22799"] = 110093,
        ["22800"] = 110094,
        ["22801"] = 110095,
        ["22802"] = 110096,
        ["22803"] = 110097,
        ["22804"] = 110098,
        ["22806"] = 110099,
        ["22807"] = 110100,
        ["22808"] = 110101,
        ["22809"] = 110102,
        ["22810"] = 110103,
        ["22811"] = 110104,
        ["22812"] = 110105,
        ["22813"] = 110106,
        ["22815"] = 110107,
        ["22816"] = 110108,
        ["22820"] = 110109,
        ["22821"] = 110110,
        ["22942"] = 110111,
        ["22988"] = 110112,
        ["23009"] = 110113,
        ["23014"] = 110114,
        ["23039"] = 110115,
        ["23044"] = 110116,
        ["23051"] = 110117,
        ["23054"] = 110118,
        ["23056"] = 110119,
        ["23221"] = 110120,
        ["23242"] = 110121,
        ["23557"] = 110133,
        ["23577"] = 110134,
        ["18881"] = 110136,
        ["19158"] = 110137,
        ["21124"] = 110138,
        ["21125"] = 110139,
        ["21127"] = 110140,
        ["22805"] = 110141,
        ["22814"] = 110142,
        ["22817"] = 110143,
        ["23362"] = 110144,
        ["32914"] = 110145,
        ["38282"] = 110146,
        ["41342"] = 110148,
        ["43267"] = 110149,
        ["50442"] = 110150,
        ["17063"] = 110259,
        ["17067"] = 110260,
        ["17078"] = 110261,
        ["17102"] = 110263,
        ["17106"] = 110264,
        ["17107"] = 110265,
        ["17782"] = 110278,
        ["18403"] = 110279,
        ["18404"] = 110280,
        ["18406"] = 110281,
        ["18813"] = 110282,
        ["18814"] = 110283,
        ["18815"] = 110284,
        ["18817"] = 110285,
        ["19137"] = 110288,
        ["19138"] = 110289,
        ["19336"] = 110290,
        ["19337"] = 110291,
        ["19339"] = 110292,
        ["19340"] = 110293,
        ["19341"] = 110294,
        ["19342"] = 110295,
        ["19343"] = 110296,
        ["19344"] = 110297,
        ["19345"] = 110298,
        ["19348"] = 110299,
        ["19349"] = 110300,
        ["19366"] = 110301,
        ["19369"] = 110302,
        ["19370"] = 110303,
        ["19371"] = 110304,
        ["19372"] = 110305,
        ["19373"] = 110306,
        ["19374"] = 110307,
        ["19375"] = 110308,
        ["19376"] = 110309,
        ["19377"] = 110310,
        ["19378"] = 110311,
        ["19379"] = 110312,
        ["19380"] = 110313,
        ["19381"] = 110314,
        ["19382"] = 110315,
        ["19383"] = 110316,
        ["19384"] = 110317,
        ["19385"] = 110318,
        ["19386"] = 110319,
        ["19387"] = 110320,
        ["19388"] = 110321,
        ["19389"] = 110322,
        ["19390"] = 110323,
        ["19391"] = 110324,
        ["19392"] = 110325,
        ["19393"] = 110326,
        ["19394"] = 110327,
        ["19395"] = 110328,
        ["19396"] = 110329,
        ["19397"] = 110330,
        ["19398"] = 110331,
        ["19399"] = 110332,
        ["19400"] = 110333,
        ["19401"] = 110334,
        ["19402"] = 110335,
        ["19403"] = 110336,
        ["19405"] = 110337,
        ["19406"] = 110338,
        ["19407"] = 110339,
        ["19430"] = 110340,
        ["19431"] = 110341,
        ["19432"] = 110342,
        ["19433"] = 110343,
        ["20600"] = 110344,
        ["20617"] = 110345,
        ["20618"] = 110346,
        ["20619"] = 110347,
        ["20623"] = 110348,
        ["20624"] = 110349,
        ["20628"] = 110350,
        ["20629"] = 110351,
        ["20630"] = 110352,
        ["20633"] = 110353,
        ["20634"] = 110354,
        ["20637"] = 110355,
        ["20638"] = 110356,
        ["20639"] = 110357,
        ["21269"] = 110364,
        ["21453"] = 110410,
        ["21454"] = 110411,
        ["21456"] = 110412,
        ["21457"] = 110413,
        ["21458"] = 110414,
        ["21460"] = 110415,
        ["21461"] = 110416,
        ["21462"] = 110417,
        ["21463"] = 110418,
        ["21464"] = 110419,
        ["21517"] = 110420,
        ["21526"] = 110421,
        ["21527"] = 110422,
        ["21529"] = 110423,
        ["21530"] = 110424,
        ["21531"] = 110425,
        ["21532"] = 110426,
        ["21579"] = 110427,
        ["21581"] = 110428,
        ["21582"] = 110429,
        ["21583"] = 110430,
        ["21585"] = 110431,
        ["21586"] = 110432,
        ["21587"] = 110433,
        ["21588"] = 110434,
        ["21596"] = 110435,
        ["21597"] = 110436,
        ["21598"] = 110437,
        ["21599"] = 110438,
        ["21600"] = 110439,
        ["21601"] = 110440,
        ["21602"] = 110441,
        ["21604"] = 110442,
        ["21605"] = 110443,
        ["21606"] = 110444,
        ["21607"] = 110445,
        ["21608"] = 110446,
        ["21609"] = 110447,
        ["21610"] = 110448,
        ["21611"] = 110449,
        ["21615"] = 110450,
        ["21617"] = 110451,
        ["21618"] = 110452,
        ["21619"] = 110453,
        ["21620"] = 110454,
        ["21621"] = 110455,
        ["21623"] = 110456,
        ["21624"] = 110457,
        ["21625"] = 110458,
        ["21626"] = 110459,
        ["21627"] = 110460,
        ["21639"] = 110461,
        ["21645"] = 110462,
        ["21647"] = 110463,
        ["21648"] = 110464,
        ["21651"] = 110465,
        ["21652"] = 110466,
        ["21663"] = 110467,
        ["21664"] = 110468,
        ["21665"] = 110469,
        ["21666"] = 110470,
        ["21667"] = 110471,
        ["21668"] = 110472,
        ["21669"] = 110473,
        ["21670"] = 110474,
        ["21671"] = 110475,
        ["21672"] = 110476,
        ["21674"] = 110477,
        ["21675"] = 110478,
        ["21676"] = 110479,
        ["21677"] = 110480,
        ["21678"] = 110481,
        ["21680"] = 110482,
        ["21681"] = 110483,
        ["21682"] = 110484,
        ["21683"] = 110485,
        ["21684"] = 110486,
        ["21685"] = 110487,
        ["21686"] = 110488,
        ["21687"] = 110489,
        ["21688"] = 110490,
        ["21689"] = 110491,
        ["21690"] = 110492,
        ["21691"] = 110493,
        ["21692"] = 110494,
        ["21693"] = 110495,
        ["21694"] = 110496,
        ["21695"] = 110497,
        ["21696"] = 110498,
        ["21697"] = 110499,
        ["21698"] = 110500,
        ["21699"] = 110501,
        ["21700"] = 110502,
        ["21701"] = 110503,
        ["21702"] = 110504,
        ["21704"] = 110505,
        ["21705"] = 110506,
        ["21706"] = 110507,
        ["21707"] = 110508,
        ["21708"] = 110509,
        ["21709"] = 110510,
        ["21710"] = 110511,
        ["21712"] = 110512,
        ["21814"] = 110513,
        ["21889"] = 110514,
        ["21890"] = 110515,
        ["21891"] = 110516,
        ["22191"] = 110517,
        ["22196"] = 110518,
        ["22402"] = 110521,
        ["22652"] = 110594,
        ["22654"] = 110595,
        ["22655"] = 110596,
        ["22658"] = 110597,
        ["22661"] = 110598,
        ["22662"] = 110599,
        ["22663"] = 110600,
        ["22664"] = 110601,
        ["22665"] = 110602,
        ["22666"] = 110603,
        ["22669"] = 110604,
        ["22670"] = 110605,
        ["22671"] = 110606,
        ["22699"] = 110607,
        ["22700"] = 110608,
        ["22701"] = 110609,
        ["22702"] = 110610,
        ["22707"] = 110611,
        ["22730"] = 110612,
        ["22731"] = 110613,
        ["22732"] = 110614,
        ["22818"] = 110615,
        ["22819"] = 110616,
        ["22935"] = 110617,
        ["22936"] = 110618,
        ["22937"] = 110619,
        ["22938"] = 110620,
        ["22939"] = 110621,
        ["22940"] = 110622,
        ["22941"] = 110623,
        ["22943"] = 110624,
        ["22947"] = 110625,
        ["22954"] = 110626,
        ["22960"] = 110627,
        ["22961"] = 110628,
        ["22967"] = 110629,
        ["22968"] = 110630,
        ["22981"] = 110631,
        ["22983"] = 110632,
        ["22994"] = 110633,
        ["23000"] = 110634,
        ["23001"] = 110635,
        ["23006"] = 110638,
        ["23017"] = 110639,
        ["23018"] = 110640,
        ["23019"] = 110641,
        ["23020"] = 110642,
        ["23021"] = 110643,
        ["23023"] = 110644,
        ["23025"] = 110645,
        ["23027"] = 110646,
        ["23028"] = 110647,
        ["23029"] = 110648,
        ["23030"] = 110649,
        ["23031"] = 110650,
        ["23032"] = 110651,
        ["23033"] = 110652,
        ["23035"] = 110653,
        ["23036"] = 110654,
        ["23037"] = 110655,
        ["23038"] = 110656,
        ["23040"] = 110657,
        ["23041"] = 110658,
        ["23042"] = 110659,
        ["23043"] = 110660,
        ["23045"] = 110661,
        ["23046"] = 110662,
        ["23047"] = 110663,
        ["23048"] = 110664,
        ["23049"] = 110665,
        ["23050"] = 110666,
        ["23053"] = 110667,
        ["23057"] = 110668,
        ["23068"] = 110678,
        ["23069"] = 110679,
        ["23070"] = 110680,
        ["23071"] = 110681,
        ["23072"] = 110682,
        ["23073"] = 110683,
        ["23075"] = 110684,
        ["23219"] = 110687,
        ["23220"] = 110688,
        ["23226"] = 110689,
        ["23237"] = 110690,
        ["23238"] = 110691,
        ["23558"] = 110697,
        ["23570"] = 110698,
        ["23663"] = 110699,
        ["23664"] = 110700,
        ["23665"] = 110701,
        ["23666"] = 110702,
        ["23667"] = 110703,
        ["23668"] = 110704,
        ["20142"] = 110714,
        ["20329"] = 110715,
        ["21339"] = 110716,
        ["21584"] = 110717,
        ["21594"] = 110718,
        ["21612"] = 110719,
        ["21613"] = 110720,
        ["21614"] = 110721,
        ["23034"] = 110722,
        ["23058"] = 110723,
        ["23363"] = 110724,
        ["5267"] = 110725,
        ["6622"] = 110726,
        ["10828"] = 110727,
        ["10836"] = 110728,
        ["10837"] = 110729,
        ["11607"] = 110730,
        ["11744"] = 110731,
        ["11786"] = 110732,
        ["11803"] = 110733,
        ["11805"] = 110734,
        ["11809"] = 110735,
        ["11816"] = 110736,
        ["11817"] = 110737,
        ["11920"] = 110738,
        ["11921"] = 110739,
        ["11922"] = 110740,
        ["11923"] = 110741,
        ["11931"] = 110742,
        ["11932"] = 110743,
        ["12532"] = 110744,
        ["12582"] = 110745,
        ["12583"] = 110746,
        ["12605"] = 110747,
        ["12621"] = 110748,
        ["12651"] = 110749,
        ["12653"] = 110750,
        ["12709"] = 110751,
        ["12776"] = 110752,
        ["12777"] = 110753,
        ["12781"] = 110754,
        ["12782"] = 110755,
        ["12783"] = 110756,
        ["12784"] = 110757,
        ["12790"] = 110758,
        ["12794"] = 110759,
        ["12796"] = 110760,
        ["12797"] = 110761,
        ["12798"] = 110762,
        ["12969"] = 110765,
        ["13000"] = 110766,
        ["13003"] = 110767,
        ["13004"] = 110768,
        ["13006"] = 110769,
        ["13015"] = 110770,
        ["13023"] = 110771,
        ["13028"] = 110772,
        ["13036"] = 110773,
        ["13040"] = 110774,
        ["13044"] = 110775,
        ["13047"] = 110776,
        ["13053"] = 110777,
        ["13056"] = 110778,
        ["13060"] = 110779,
        ["13146"] = 110780,
        ["13148"] = 110781,
        ["13161"] = 110782,
        ["13163"] = 110783,
        ["13167"] = 110784,
        ["13182"] = 110785,
        ["13198"] = 110787,
        ["13204"] = 110788,
        ["13246"] = 110790,
        ["13248"] = 110791,
        ["13249"] = 110792,
        ["13285"] = 110793,
        ["13286"] = 110794,
        ["13348"] = 110795,
        ["13349"] = 110796,
        ["13360"] = 110797,
        ["13361"] = 110798,
        ["13368"] = 110799,
        ["13372"] = 110800,
        ["13380"] = 110801,
        ["13393"] = 110802,
        ["13396"] = 110803,
        ["13399"] = 110804,
        ["13401"] = 110805,
        ["13408"] = 110806,
        ["13534"] = 110807,
        ["13938"] = 110808,
        ["13952"] = 110809,
        ["13953"] = 110810,
        ["13964"] = 110811,
        ["13982"] = 110812,
        ["13983"] = 110813,
        ["13984"] = 110814,
        ["14024"] = 110815,
        ["14487"] = 110816,
        ["14531"] = 110817,
        ["14541"] = 110818,
        ["14576"] = 110819,
        ["15418"] = 110820,
        ["15800"] = 110821,
        ["15801"] = 110822,
        ["15806"] = 110823,
        ["15853"] = 110824,
        ["15854"] = 110825,
        ["16007"] = 110826,
        ["16039"] = 110827,
        ["16996"] = 110828,
        ["16997"] = 110829,
        ["17015"] = 110830,
        ["17016"] = 110831,
        ["18044"] = 110832,
        ["18048"] = 110833,
        ["18310"] = 110834,
        ["18311"] = 110835,
        ["18321"] = 110836,
        ["18323"] = 110837,
        ["18324"] = 110838,
        ["18338"] = 110839,
        ["18372"] = 110840,
        ["18376"] = 110841,
        ["18388"] = 110842,
        ["18392"] = 110843,
        ["18396"] = 110844,
        ["18420"] = 110845,
        ["18483"] = 110846,
        ["18484"] = 110847,
        ["18491"] = 110848,
        ["18498"] = 110849,
        ["18502"] = 110850,
        ["18520"] = 110851,
        ["18531"] = 110852,
        ["18534"] = 110853,
        ["18671"] = 110854,
        ["18680"] = 110855,
        ["18683"] = 110856,
        ["18717"] = 110857,
        ["18725"] = 110858,
        ["18729"] = 110859,
        ["18737"] = 110860,
        ["18738"] = 110861,
        ["18755"] = 110862,
        ["18758"] = 110863,
        ["18759"] = 110864,
        ["18761"] = 110865,
        ["19106"] = 110872,
        ["19107"] = 110873,
        ["19108"] = 110874,
        ["19900"] = 110884,
        ["19901"] = 110885,
        ["19908"] = 110886,
        ["19946"] = 110888,
        ["19961"] = 110889,
        ["19962"] = 110890,
        ["19963"] = 110891,
        ["19964"] = 110892,
        ["19965"] = 110893,
        ["19967"] = 110894,
        ["19968"] = 110895,
        ["19993"] = 110896,
        ["20258"] = 110897,
        ["20646"] = 110898,
        ["20647"] = 110899,
        ["20648"] = 110900,
        ["20654"] = 110901,
        ["20657"] = 110902,
        ["20660"] = 110903,
        ["20663"] = 110904,
        ["20666"] = 110905,
        ["20669"] = 110906,
        ["20672"] = 110907,
        ["20675"] = 110908,
        ["20696"] = 110909,
        ["20720"] = 110910,
        ["20722"] = 110911,
        ["21800"] = 110912,
        ["21801"] = 110913,
        ["21802"] = 110914,
        ["21806"] = 110915,
        ["22208"] = 110916,
        ["22254"] = 110917,
        ["22266"] = 110918,
        ["22314"] = 110919,
        ["22315"] = 110920,
        ["22317"] = 110921,
        ["22318"] = 110922,
        ["22322"] = 110923,
        ["22332"] = 110924,
        ["22333"] = 110925,
        ["22335"] = 110926,
        ["22347"] = 110927,
        ["22348"] = 110928,
        ["22377"] = 110929,
        ["22378"] = 110930,
        ["22379"] = 110931,
        ["22380"] = 110932,
        ["22394"] = 110933,
        ["22404"] = 110934,
        ["22406"] = 110935,
        ["22408"] = 110936,
        ["22688"] = 110937,
        ["22713"] = 110938,
        ["23124"] = 110939,
        ["23132"] = 110940,
        ["24222"] = 110941,
        ["28972"] = 110942,
        ["12795"] = 110943,
        ["12802"] = 110944,
        ["20368"] = 110946,
        ["24071"] = 110947,
        ["29210"] = 110948,
        ["30418"] = 110949,
        ["1973"] = 110950,
        ["4696"] = 110951,
        ["9402"] = 110952,
        ["10829"] = 110953,
        ["10833"] = 110954,
        ["10835"] = 110955,
        ["11604"] = 110956,
        ["11669"] = 110957,
        ["11735"] = 110962,
        ["11745"] = 110963,
        ["11746"] = 110964,
        ["11755"] = 110965,
        ["11768"] = 110970,
        ["11782"] = 110971,
        ["11783"] = 110972,
        ["11785"] = 110973,
        ["11787"] = 110974,
        ["11802"] = 110975,
        ["11807"] = 110976,
        ["11810"] = 110977,
        ["11812"] = 110978,
        ["11814"] = 110979,
        ["11815"] = 110980,
        ["11819"] = 110981,
        ["11820"] = 110982,
        ["11821"] = 110983,
        ["11822"] = 110984,
        ["11823"] = 110985,
        ["11832"] = 110986,
        ["11924"] = 110987,
        ["11925"] = 110988,
        ["11926"] = 110989,
        ["11927"] = 110990,
        ["11928"] = 110991,
        ["11929"] = 110992,
        ["11930"] = 110993,
        ["11933"] = 110994,
        ["11935"] = 110996,
        ["12059"] = 110997,
        ["12103"] = 110998,
        ["12543"] = 111000,
        ["12544"] = 111001,
        ["12545"] = 111002,
        ["12547"] = 111003,
        ["12548"] = 111004,
        ["12551"] = 111005,
        ["12553"] = 111006,
        ["12554"] = 111007,
        ["12556"] = 111008,
        ["12557"] = 111009,
        ["12587"] = 111010,
        ["12588"] = 111011,
        ["12589"] = 111012,
        ["12602"] = 111013,
        ["12603"] = 111014,
        ["12604"] = 111015,
        ["12606"] = 111016,
        ["12608"] = 111017,
        ["12609"] = 111018,
        ["12618"] = 111019,
        ["12619"] = 111020,
        ["12620"] = 111021,
        ["12625"] = 111022,
        ["12626"] = 111023,
        ["12628"] = 111024,
        ["12631"] = 111025,
        ["12632"] = 111026,
        ["12633"] = 111027,
        ["12634"] = 111028,
        ["12636"] = 111029,
        ["12637"] = 111030,
        ["12905"] = 111031,
        ["12927"] = 111033,
        ["12929"] = 111034,
        ["12930"] = 111035,
        ["12935"] = 111036,
        ["12936"] = 111037,
        ["12963"] = 111041,
        ["12964"] = 111042,
        ["12965"] = 111043,
        ["12966"] = 111044,
        ["12967"] = 111045,
        ["12968"] = 111046,
        ["12970"] = 111047,
        ["13001"] = 111048,
        ["13002"] = 111049,
        ["13007"] = 111050,
        ["13013"] = 111051,
        ["13070"] = 111052,
        ["13072"] = 111053,
        ["13075"] = 111054,
        ["13077"] = 111055,
        ["13080"] = 111056,
        ["13083"] = 111057,
        ["13090"] = 111058,
        ["13091"] = 111059,
        ["13092"] = 111060,
        ["13096"] = 111061,
        ["13098"] = 111062,
        ["13101"] = 111063,
        ["13107"] = 111064,
        ["13113"] = 111065,
        ["13116"] = 111066,
        ["13118"] = 111067,
        ["13123"] = 111068,
        ["13130"] = 111069,
        ["13133"] = 111070,
        ["13135"] = 111071,
        ["13141"] = 111072,
        ["13142"] = 111073,
        ["13162"] = 111074,
        ["13164"] = 111075,
        ["13166"] = 111076,
        ["13168"] = 111077,
        ["13169"] = 111078,
        ["13170"] = 111079,
        ["13177"] = 111080,
        ["13178"] = 111081,
        ["13179"] = 111082,
        ["13181"] = 111083,
        ["13184"] = 111084,
        ["13185"] = 111085,
        ["13203"] = 111086,
        ["13205"] = 111087,
        ["13206"] = 111088,
        ["13208"] = 111089,
        ["13210"] = 111091,
        ["13211"] = 111092,
        ["13212"] = 111093,
        ["13213"] = 111094,
        ["13243"] = 111095,
        ["13244"] = 111096,
        ["13252"] = 111097,
        ["13253"] = 111098,
        ["13255"] = 111100,
        ["13257"] = 111101,
        ["13259"] = 111103,
        ["13260"] = 111104,
        ["13261"] = 111105,
        ["13282"] = 111106,
        ["13283"] = 111107,
        ["13284"] = 111108,
        ["13340"] = 111109,
        ["13344"] = 111110,
        ["13345"] = 111111,
        ["13346"] = 111112,
        ["13358"] = 111113,
        ["13359"] = 111114,
        ["13369"] = 111115,
        ["13373"] = 111116,
        ["13374"] = 111117,
        ["13375"] = 111118,
        ["13376"] = 111119,
        ["13378"] = 111120,
        ["13379"] = 111121,
        ["13381"] = 111122,
        ["13382"] = 111123,
        ["13383"] = 111124,
        ["13384"] = 111125,
        ["13385"] = 111126,
        ["13394"] = 111134,
        ["13395"] = 111135,
        ["13397"] = 111136,
        ["13398"] = 111137,
        ["13400"] = 111138,
        ["13402"] = 111139,
        ["13403"] = 111140,
        ["13404"] = 111141,
        ["13405"] = 111142,
        ["13498"] = 111144,
        ["13502"] = 111145,
        ["13515"] = 111146,
        ["13524"] = 111147,
        ["13529"] = 111148,
        ["13936"] = 111149,
        ["13944"] = 111150,
        ["13950"] = 111151,
        ["13951"] = 111152,
        ["13954"] = 111153,
        ["13955"] = 111154,
        ["13956"] = 111155,
        ["13957"] = 111156,
        ["13958"] = 111157,
        ["13959"] = 111158,
        ["13960"] = 111159,
        ["13961"] = 111160,
        ["13962"] = 111161,
        ["13963"] = 111162,
        ["13965"] = 111163,
        ["13966"] = 111164,
        ["13967"] = 111165,
        ["13968"] = 111166,
        ["13969"] = 111167,
        ["13986"] = 111168,
        ["14002"] = 111169,
        ["14022"] = 111170,
        ["14023"] = 111171,
        ["14136"] = 111172,
        ["14137"] = 111173,
        ["14138"] = 111174,
        ["14139"] = 111175,
        ["14140"] = 111176,
        ["14340"] = 111177,
        ["14502"] = 111178,
        ["14503"] = 111179,
        ["14522"] = 111180,
        ["14525"] = 111181,
        ["14528"] = 111182,
        ["14536"] = 111183,
        ["14537"] = 111184,
        ["14538"] = 111185,
        ["14539"] = 111186,
        ["14543"] = 111187,
        ["14545"] = 111188,
        ["14548"] = 111189,
        ["14577"] = 111190,
        ["15047"] = 111211,
        ["15059"] = 111219,
        ["15060"] = 111220,
        ["15065"] = 111223,
        ["15138"] = 111225,
        ["15411"] = 111226,
        ["15413"] = 111227,
        ["15421"] = 111228,
        ["15799"] = 111229,
        ["15802"] = 111230,
        ["15805"] = 111231,
        ["15855"] = 111232,
        ["15856"] = 111233,
        ["15857"] = 111234,
        ["15873"] = 111235,
        ["16058"] = 111236,
        ["16337"] = 111239,
        ["16998"] = 111370,
        ["16999"] = 111371,
        ["17044"] = 111372,
        ["17045"] = 111373,
        ["17061"] = 111374,
        ["17759"] = 111393,
        ["18022"] = 111398,
        ["18043"] = 111399,
        ["18047"] = 111400,
        ["18102"] = 111401,
        ["18103"] = 111402,
        ["18104"] = 111403,
        ["18289"] = 111404,
        ["18296"] = 111405,
        ["18298"] = 111406,
        ["18309"] = 111407,
        ["18312"] = 111408,
        ["18313"] = 111409,
        ["18314"] = 111410,
        ["18315"] = 111411,
        ["18317"] = 111412,
        ["18318"] = 111413,
        ["18322"] = 111415,
        ["18325"] = 111416,
        ["18326"] = 111417,
        ["18327"] = 111418,
        ["18328"] = 111419,
        ["18340"] = 111420,
        ["18344"] = 111421,
        ["18354"] = 111422,
        ["18366"] = 111423,
        ["18367"] = 111424,
        ["18368"] = 111425,
        ["18369"] = 111426,
        ["18370"] = 111427,
        ["18371"] = 111428,
        ["18373"] = 111429,
        ["18374"] = 111430,
        ["18375"] = 111431,
        ["18377"] = 111432,
        ["18378"] = 111433,
        ["18379"] = 111434,
        ["18380"] = 111435,
        ["18381"] = 111436,
        ["18383"] = 111438,
        ["18384"] = 111439,
        ["18385"] = 111440,
        ["18386"] = 111441,
        ["18387"] = 111442,
        ["18389"] = 111443,
        ["18390"] = 111444,
        ["18391"] = 111445,
        ["18393"] = 111446,
        ["18394"] = 111447,
        ["18395"] = 111448,
        ["18397"] = 111449,
        ["18398"] = 111450,
        ["18399"] = 111451,
        ["18407"] = 111452,
        ["18408"] = 111453,
        ["18409"] = 111454,
        ["18413"] = 111455,
        ["18421"] = 111456,
        ["18424"] = 111457,
        ["18485"] = 111476,
        ["18486"] = 111477,
        ["18490"] = 111478,
        ["18493"] = 111479,
        ["18494"] = 111480,
        ["18495"] = 111481,
        ["18496"] = 111482,
        ["18497"] = 111483,
        ["18499"] = 111484,
        ["18500"] = 111485,
        ["18503"] = 111486,
        ["18504"] = 111487,
        ["18505"] = 111488,
        ["18506"] = 111489,
        ["18507"] = 111490,
        ["18508"] = 111491,
        ["18521"] = 111492,
        ["18522"] = 111493,
        ["18523"] = 111494,
        ["18524"] = 111495,
        ["18525"] = 111496,
        ["18526"] = 111497,
        ["18527"] = 111498,
        ["18528"] = 111499,
        ["18530"] = 111501,
        ["18532"] = 111502,
        ["18533"] = 111503,
        ["18535"] = 111504,
        ["18536"] = 111505,
        ["18537"] = 111506,
        ["18602"] = 111507,
        ["18673"] = 111508,
        ["18676"] = 111509,
        ["18678"] = 111510,
        ["18681"] = 111511,
        ["18682"] = 111512,
        ["18686"] = 111514,
        ["18689"] = 111515,
        ["18690"] = 111516,
        ["18691"] = 111517,
        ["18692"] = 111518,
        ["18693"] = 111519,
        ["18694"] = 111520,
        ["18695"] = 111521,
        ["18696"] = 111522,
        ["18698"] = 111523,
        ["18699"] = 111524,
        ["18700"] = 111525,
        ["18701"] = 111526,
        ["18702"] = 111527,
        ["18716"] = 111528,
        ["18718"] = 111529,
        ["18720"] = 111530,
        ["18721"] = 111531,
        ["18722"] = 111532,
        ["18723"] = 111533,
        ["18726"] = 111534,
        ["18727"] = 111535,
        ["18728"] = 111536,
        ["18730"] = 111537,
        ["18734"] = 111538,
        ["18735"] = 111539,
        ["18736"] = 111540,
        ["18739"] = 111541,
        ["18740"] = 111542,
        ["18741"] = 111543,
        ["18742"] = 111544,
        ["18743"] = 111545,
        ["18744"] = 111546,
        ["18745"] = 111547,
        ["18754"] = 111548,
        ["18756"] = 111549,
        ["18757"] = 111550,
        ["18760"] = 111551,
        ["18807"] = 111552,
        ["17982"] = 111569,
        ["19043"] = 111570,
        ["19044"] = 111571,
        ["19047"] = 111572,
        ["19048"] = 111573,
        ["19049"] = 111574,
        ["19050"] = 111575,
        ["19051"] = 111576,
        ["19052"] = 111577,
        ["19056"] = 111578,
        ["19057"] = 111579,
        ["19058"] = 111580,
        ["19059"] = 111581,
        ["19109"] = 111599,
        ["19111"] = 111600,
        ["19112"] = 111601,
        ["19113"] = 111602,
        ["19869"] = 111645,
        ["19870"] = 111646,
        ["19871"] = 111647,
        ["19875"] = 111649,
        ["19877"] = 111650,
        ["19878"] = 111651,
        ["19886"] = 111652,
        ["19887"] = 111653,
        ["19888"] = 111654,
        ["19889"] = 111655,
        ["19892"] = 111656,
        ["19894"] = 111658,
        ["19895"] = 111659,
        ["19899"] = 111661,
        ["19906"] = 111663,
        ["19907"] = 111664,
        ["19913"] = 111666,
        ["19915"] = 111667,
        ["19919"] = 111668,
        ["19922"] = 111670,
        ["19923"] = 111671,
        ["19928"] = 111673,
        ["19929"] = 111674,
        ["19930"] = 111675,
        ["19947"] = 111676,
        ["19979"] = 111677,
        ["20213"] = 111706,
        ["20215"] = 111707,
        ["20216"] = 111708,
        ["20217"] = 111709,
        ["20218"] = 111710,
        ["20219"] = 111711,
        ["20259"] = 111712,
        ["20260"] = 111713,
        ["20261"] = 111714,
        ["20262"] = 111715,
        ["20263"] = 111716,
        ["20265"] = 111717,
        ["20266"] = 111718,
        ["20476"] = 111720,
        ["20477"] = 111721,
        ["20478"] = 111722,
        ["20479"] = 111723,
        ["20480"] = 111724,
        ["20481"] = 111725,
        ["20537"] = 111726,
        ["20538"] = 111727,
        ["20539"] = 111728,
        ["20549"] = 111729,
        ["20550"] = 111730,
        ["20551"] = 111731,
        ["20665"] = 111732,
        ["20668"] = 111733,
        ["20671"] = 111734,
        ["20674"] = 111735,
        ["20680"] = 111736,
        ["20681"] = 111737,
        ["20683"] = 111738,
        ["20684"] = 111739,
        ["20686"] = 111740,
        ["20687"] = 111741,
        ["20689"] = 111742,
        ["20690"] = 111743,
        ["20695"] = 111744,
        ["20697"] = 111745,
        ["20699"] = 111746,
        ["20700"] = 111747,
        ["20701"] = 111748,
        ["20702"] = 111749,
        ["20703"] = 111750,
        ["20704"] = 111751,
        ["20705"] = 111752,
        ["20706"] = 111753,
        ["20707"] = 111754,
        ["20710"] = 111755,
        ["20711"] = 111756,
        ["20712"] = 111757,
        ["20713"] = 111758,
        ["20714"] = 111759,
        ["20715"] = 111760,
        ["20716"] = 111761,
        ["20717"] = 111762,
        ["20721"] = 111763,
        ["21178"] = 111764,
        ["21179"] = 111765,
        ["21181"] = 111766,
        ["21182"] = 111767,
        ["21183"] = 111768,
        ["21187"] = 111769,
        ["21455"] = 111770,
        ["21468"] = 111771,
        ["21469"] = 111772,
        ["21470"] = 111773,
        ["21473"] = 111774,
        ["21474"] = 111775,
        ["21475"] = 111776,
        ["21476"] = 111777,
        ["21477"] = 111778,
        ["21480"] = 111779,
        ["21481"] = 111780,
        ["21482"] = 111781,
        ["21483"] = 111782,
        ["21484"] = 111783,
        ["21488"] = 111784,
        ["21489"] = 111785,
        ["21490"] = 111786,
        ["21491"] = 111787,
        ["21494"] = 111788,
        ["21495"] = 111789,
        ["21496"] = 111790,
        ["21497"] = 111791,
        ["21500"] = 111792,
        ["21501"] = 111793,
        ["21502"] = 111794,
        ["21503"] = 111795,
        ["21779"] = 111796,
        ["21791"] = 111797,
        ["21792"] = 111798,
        ["21803"] = 111799,
        ["21804"] = 111800,
        ["21805"] = 111801,
        ["21809"] = 111802,
        ["21810"] = 111803,
        ["22149"] = 111840,
        ["22150"] = 111841,
        ["22195"] = 111842,
        ["22197"] = 111843,
        ["22204"] = 111844,
        ["22205"] = 111845,
        ["22207"] = 111846,
        ["22212"] = 111847,
        ["22231"] = 111849,
        ["22232"] = 111850,
        ["22241"] = 111851,
        ["22242"] = 111852,
        ["22245"] = 111853,
        ["22247"] = 111854,
        ["22253"] = 111855,
        ["22255"] = 111856,
        ["22256"] = 111857,
        ["22257"] = 111858,
        ["22267"] = 111859,
        ["22268"] = 111860,
        ["22269"] = 111861,
        ["22271"] = 111862,
        ["22275"] = 111863,
        ["22319"] = 111872,
        ["22321"] = 111873,
        ["22325"] = 111874,
        ["22326"] = 111875,
        ["22327"] = 111876,
        ["22328"] = 111877,
        ["22329"] = 111878,
        ["22330"] = 111879,
        ["22331"] = 111880,
        ["22334"] = 111881,
        ["22336"] = 111882,
        ["22337"] = 111883,
        ["22339"] = 111884,
        ["22340"] = 111885,
        ["22342"] = 111886,
        ["22343"] = 111887,
        ["22400"] = 111892,
        ["22401"] = 111893,
        ["22403"] = 111894,
        ["22405"] = 111895,
        ["22407"] = 111896,
        ["22409"] = 111897,
        ["22410"] = 111898,
        ["22411"] = 111899,
        ["22412"] = 111900,
        ["22433"] = 111901,
        ["22472"] = 111902,
        ["22660"] = 111903,
        ["22680"] = 111904,
        ["22681"] = 111905,
        ["22689"] = 111906,
        ["22690"] = 111907,
        ["22711"] = 111908,
        ["22712"] = 111909,
        ["22714"] = 111910,
        ["22715"] = 111911,
        ["22716"] = 111912,
        ["22718"] = 111913,
        ["22720"] = 111914,
        ["22725"] = 111915,
        ["22756"] = 111916,
        ["22757"] = 111917,
        ["22758"] = 111918,
        ["22759"] = 111919,
        ["22760"] = 111920,
        ["22761"] = 111921,
        ["22762"] = 111922,
        ["22763"] = 111923,
        ["22764"] = 111924,
        ["23125"] = 111969,
        ["23126"] = 111970,
        ["23127"] = 111971,
        ["23128"] = 111972,
        ["23129"] = 111973,
        ["23139"] = 111974,
        ["23156"] = 111975,
        ["23201"] = 111980,
        ["23203"] = 111981,
        ["32863"] = 112062,
        ["34424"] = 112064,
        ["34423"] = 112065,
        ["21780"] = 112068,
        ["21793"] = 112069,
        ["12105"] = 112094,
        ["19065"] = 112095
    }

    function ExclusiveSpells(event, player, oldLevel)
        local level = player:GetLevel();
        local class;
        if(level > oldLevel)then
           class =  player:GetClassAsString();
            lvltable = EXSpellLevelTable[class];
            idtable = EXSpellTable[class];
            for i = 1 , #idtable do
                print(idtable[i])
                if(lvltable[i] == level )then
                    player:ServerLearnSpell(idtable[i])
                end
                if(lvltable[i] > level )then
                    break;
                end

            end
        end

    end
    local MyHandlers = AIO.AddHandlers("SuperTalents", {SUPERLearnSpell,SUPERUNLearnSpell,superenchant})


    function MyHandlers.SUPERLearnSpell(player, p1, p2)
        print("learning spell"..p1.." p2: "..p2)
        local id = SpellTable[p1][p2];
        if (id)then
            if(SpellLevelTable[p1][p2] <= player:GetLevel())then
                print("learning spell".. id)
                player:LearnSpell(id,false)
            end
        end
    end

    function MyHandlers.SUPERUNLearnSpell(player, p1,p2)
        local id = SpellTable[p1][p2];
        print(id)
        if (id)then
            if(player:HasSpell(id) == true)then
                print("YO")
                player:UnLearnSpell(id,false)
            end
        end
    end

    function MyHandlers.superenchant(player,enchant,slot)
        local i = 1;
        local  item = nil;
        while item == nil do
            item= player:GetItemByPos( 255, i );
            item:IsLocked()
            i = i + 1;
        end
        print(item:GetName())
        if(slot == 1)then
            print(item:SetEnchantment(enchant,9));
        end
        if(slot == 2)then
            print(item:SetEnchantment(enchant,10));
        end
        if(slot == 3)then
            print(item:SetEnchantment(enchant,11));
        end
        if(slot < 0)then
            print(item:SetEnchantment(enchant,slot*-1));
        end
        if(slot == 0 )then
            print(item:SetEnchantment(enchant,slot));

        end
    end

    RegisterPlayerEvent(13, ExclusiveSpells )

else

    -- we are on client
    print("AIO_LOADED")
	--loaded, reason = LoadAddOn("Nog_Base")
	LoadAddOn("Nog_Base")
	--LoadAddOn("Nog_Base")
	--LoadAddOn("Nog_Base")
	--LoadAddOn("Nog_Base")


	if(reason == nil)then

	else
	print("you are missing a Required Addon , you will be logged out soon");
	end
    function AIO_LearnSpell(p1,p2)
        print("sending Learn "..tostring(Nog_Selected_Spell.info.name))
        AIO.Handle("SuperTalents", "SUPERLearnSpell",p1,p2)
    end
    function AIO_UnLearnSpell(p1,p2)
        print("sending Unlearn "..Nog_Learn_Selected_Spell.info.name)
        AIO.Handle("SuperTalents", "SUPERUNLearnSpell",p1,p2)
    end
    function AIO_SetEnchant(enchant,item)
        -- print("sending Unlearn "..Nog_Learn_Selected_Spell.info.name)
        AIO.Handle("SuperTalents", "superenchant",enchant,item)
    end
end




    