---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Admin.
--- DateTime: 05.06.2019 05:55
---


local AIO = AIO or require("AIO")

if AIO.AddAddon() then
    -- we are on server
    print("___________________GLOBALVARS")
    SpellLevelTable ={

        Arms = {
            1,	--BattleStance
            1,		--Heroic Strike
            --4, 	--Charge
            4,	--Rend
            6,	--Thunder Clap
            8,	--HarmString
            12,	--Overpower
            16,	--Mocking Blow
            20,	--Retaliation
            71,	--Shattering throw
            61,	--heroic Throw
        },
        Furor = {

            1,	--Battlesout
            6,	--Victory Rush
            --14,	--Demo Shout
            20,	--Cleave
            --22,	--Intimidating Shout
            24, 	--Execute
            26,	--ChallengingShout
            30,	--BeserkerStance
            30,	--Death Wish
            30,	--Intercept
            30,	--Slam
            32,	--Beserker rage
            36,	--Whirlwind
            --38,	--Pummel
            50,	--Recklessness
            54,	--Commanding shout
            75,	--Enraged Regeneration
        },
        Protection = {
            10, 	--Bloodrage
            10,	--Sunder Armor
            10,	--Taunt
            12,		--Shield Bash
            14,	--Revenge
            16,	--Shield Block
            18,	--Disarm
            20,	--Stance Mastery
            28,	--ShieldWall
            40,	--Shield Slam
            64,	--Spell reflect
            70,	--Intervene
        },

        Arcane = {
            1,	--Arcane Intellect
            4,	--Conjure Water
            6,	--Conjure Food
            8,	--Arcane Missles
            --8,	--Polymorph
            10,	--Dampen Magic
            12,	--Slow Fall
            14,	--Arcane Explosion
            18,	--Amplify Magic
            18,	--Remove Curse
            --20,	--Blink
            20,	--Evocation
            20,	--ManaShield
            --24,	--CounterSpell
            28,	--Conjure Mana Gem
            34,	--Mage Armor
            64,	--Arcane Blast
            68,		--Invisibility
            70,	--Ritual of Refreshment
            70,	--Spellsteal
            78,	--Mirror Image
        },
        Fire = {
            1,	--Fireball
            6,	--Fire Blast
            16,	--FlameStrike
            20,	--Fire Ward
            22,	--Scorch
            66,	--Molten Armor
            72,	--Frostfire Bolt
        },
        FrostMage = {
            4,	--FrostBolt
            10,	--Frost Nova
            20,		--Blizzard
            22,	--Frost Ward
            26,	--Cone of Cold
            --30,	--Ice Armor
            --30,	--Ice Block
            66,	--Ice Lance
        },

        Assasination = {
            1,	--Eviscerate
            10,	--Slice and Dice
            14,	--Expose Armor
            --	14,	--Garrote
            --	18,	--Ambush
            20,	--Dismantle
            20,	--Rupture
            --	26,	--Cheap shot
            30,	--Kidney Shot
            66,	--Evenom
            66,	--Deadly Throw
        },
        Combat = {
            1,	--Sinister Strike
            1,		--BackStab
            6,	--Gouge
            --	8,	--Evasion
            10,	--Sprint
            --	12,	--Kick
            16,	--Feint
            66,	--Shiv
            66,	--Fan of Knives
        },
        Subletly = {
            --	1,	--Stealth
            --	4,	--Pick Pocket
            --	10,	--Sap
            20,	--Ghostly Strike
            22,	--Distract
            22,	--Vanish
            24,	--Detect Traps
            30,	--Disarm Trap
            --	34,	--Blind
            40,	--Safe Fall
            66,	--Cloak of Shadows
            66,	--Tricks of the Trade
        },


        Balance = {
            1, --Wrath
            4, --Moonfire
            6, --Thorns
            --	8, --Entangliing Roots
            10, --Natures Grasp
            18, --Faerie Fire
            18, --Hibernate
            20, --Starfire
            22,  --Soothe Animal
            40, --Hurricane
            --	40, --Innervate
            --	44,  --Barkskin
            70 --Cyclone
        },
        Feral = {
            10,      --BearForm
            10,		--Demo Roar
            10,     --Growl
            10,     --maul
            12,	    --Enrage
            14, --Bash
            --	16,	--Aquatic Form
            16,	--Swipe[Bear]
            --	16,	--Travel Form
            16,	--Faeri Fire Feral
            20,	--Cat Form
            20,	--Claw
            --	20,	--Prowl
            20,	--Rip
            22,	--Shred
            24,	--Rake
            24,	--Tigers Fury
            26,	--Dash
            28,	--Challenging Roar
            28,	--Cower
            32,	--Ferocious Bite
            32,	--Ravage
            --	32,	--Track Humanoids
            36,	--Frenzied Regeneration
            36,	--Pounce
            40,	--Faelin Grace
            40,	--Savage Defense
            --	61,	--Flight Form
            62,	--Maim
            66,	--Lacerate
            77,	--Swipe Cat
        },
        Restoration = {
            1, 	--Healing Touch
            1,	--Mark of the Wild
            4,	--Rejuvenation
            12,	--Regrowth
            12,	--Revive
            --	20,	--Rebirth
            24,	--Remove Curse
            26,	--Abolish Poison
            30,	--Tranqility
            50,	--Gift of the Wild
            64,	--Lifebloom
            80,	--Nourish
        },

        BeastMaster = {
            --	4,	--Aspect of the Monkey
            10,	--Aspect of the Hawk
            --	10,	--Call PET
            --	10,	--Dismiss PET
            --	10,	--Feed PET
            --	10,	--Revive PET
            --	10,	--Tame Beast
            --	12,	--Mend PET
            --	14,	--Eagle Eye
            --	14,	--Eye of the Beast
            14,	--Scare Beast
            --	16,	--Aspect of the Cheetah
            18,	--Aspect of the Vipper
            24,	--Beast Lore
            30,	--Aspect of the Beast
            --	40,	--Aspect of the Pack
            46,	--Aspect of the Wild
            66,	--Kill Command
            66,	--Aspect of the Dragonhawk
            66,	--Masters Call
            --	66,	--Call Stabled Pet

        },
        Marksman = {
            1,  --AutoShot
            4,	--[Serpent Sting]
            6,	--[Arcane Shot]
            --	6,	--[Hunter's Mark]
            8,	--[Concussive Shot]
            12,	--[Distracting Shot]
            18,	--[Multi-Shot]
            22,	--[Scorpid Sting]
            26,	--[Rapid Fire]
            --	32,	--[Flare]
            36,	--[Viper Sting]
            40,	--[Volley]
            50,	--[Steady Shot]
            60,	--[Tranquilizing Shot]
            71,	--[Kill Shot]
        },
        Survival = {
            1,  --RaptorStrike
            --	1,	--Track Beasts]
            --	10,	--Track Humanoids]
            12,	--Wing Clip]
            1,	--Immolation Trap]
            16,	--Mongoose Bite]
            --	18,	--Track Undead]
            20	,	--Disengage]
            20,	--Freezing Trap]
            --	24,	--Track Hidden]
            --	26,	--Track Elementals]
            28,	--Frost Trap]
            30,	--Feign Death]
            --	32,	--Track Demons]
            34,	--Explosive Trap]
            --	40,	--Track Giants]
            --	50,	--Track Dragonkin]
            60,	--Deterrence]
            66,	--Snake Trap
            66,	--Misdirection]
            66,	--Freezing Arrow]
        },

        Elemental = {

            1,	--Lightning Bolt
            4,	--Earth Shock
            --	6,	--Earthbind Totem
            8,	--Stoneclaw Totem
            10,	--Fame Shock
            10,	--Searing Totem
            12,	--Fire Nova
            --	12,	--Purge
            --	16,	--Wind Shear
            --	20,	--Frost Shock
            26,	--Magma Totem
            30,	--Call of the Elements
            32, 	--Chain Lightning
            30,	--Call of the Ancestors
            30,	--Call of the Spirits
            68,	--Fire Ele Totem
            68,	--Lava Burst
            68,	--Hex

        },
        Enhancement = {
            1, 	--Rockbiter
            4,	--StoneSkin Totem
            8,	--Lightning Shield
            10,	--Flametongue Wpn
            10,	--Strenght of Earth Totem
            16,	--Ghost Wolf
            20,	--Frostbrand Wpn
            22,	--Water Breathing
            24,	--Frost Resistance totem
            --	26,	--Far Sight
            28,	--Fire Resistance Totem
            28,	--Flametongue Totem
            28,	--Water Walking
            30,	--Astral Recall
            --	30,	--Grounding Totem
            30,	--Nature Resi Totem
            --	30,	--Windfury Wpn
            32,	--Windfury Totem
            34,	--Sentry Totem
            64,	--Wrath of the Air Totem
            66,	--Earth Ele Totem
            66,	--Bloodlust
            67,	--Heroism
        },
        ShamanResto= {
            1,	--Healing Wave
            12,	--Ancestral Spirit
            16,	--Cure Toxins
            18,	--Tremor Totem
            20,	--Healing Stream Totem
            20,	--Lesser Healing Wave
            20,	--Water Shield
            --	26,	--Mana Spring Totem
            30,	--Earthliving Wpn
            --	30,	--Reincarnation
            30,	--Totemic Recall
            --	40, 	--Cleansing Totem
            40,	--Chain Heal

        },

        Disci = {
            1,	--Power Word Fort
            6,		--PowerWord Shield
            --	12,	--Inner Fire
            --	18,	--Dispel Magic
            --	20,	--Fear Ward
            20,	--Shacke Undead
            24,	--Mana Burn
            30,	--Divine Spirit
            34,	--Levitate,
            70,	--Mass Dispel

        },
        PriestHoly = {
            8,	--Renew
            10,	--Ressurection
            14,	--Cure Disease
            16,	--Heal
            20,	--Flash Heal
            20,	--Holy Fire
            --	20,	--Holy Nova
            30,	--Prayer of Healing
            32,	--Abolish Disease
            40,	--Greater Heal
            64,	--Binding Heal
            68,	--Prayer of Mending
            70,	--Divine Hymn
            70,	--Hymn of Hope
        },
        Shadow = {
            4, 	--Shadow Word Pain
            8,	--Fade
            10,	--Mind Blast
            --	14,	--Psychic Scream
            20,	--Devo Plague
            20,	--Mind Soothe
            22,	--Mind Vision
            30,	--Mind Control
            30,	--ShadowProtection
            62,	--Shadow word Death
            66,	--Shadowfiend
            72,	--Mind Sear
        },

        Affliction = {
            4,	--Corruption
            4,	--Curse of Weakness
            --	6,	--Life Tap
            --	8,	--Curse of Agony
            --	8,	--Fear
            14,	--Drain Soul
            14,	--Drain Life
            24,	--Drain Mana
            26,	--Curse of Tongues
            --	32,	--Curse of the Elements
            40,	--Howl of Terror
            --	42,	--Death Coil
            60,	--Curse of Doom
            70,	--Seed of Corruption
        },
        Demonology = {
            --	1,	--Demon Skin
            --	1,	--Summon Imp
            10, 	--Create Healthstone
            12,	    --Health Funnel
            16,	--Unending Breath
            18,	--Create Soulstone
            22,	--Eye of Kilrogg
            24,	--Sense Demons
            26,	--Detect invis
            --	28,	--Banish
            28,	--Create Firestone
            30,	--Enslave Demon
            32,	--Shadow Ward
            36,	--Create SpellStone
            62,	--Fel Armor
            66,	--Soulshatter
            68,	--Ritual of Soulshatter
            80,	--Demonic Circle Summon
            80,	--Demonic Circle Teleport
        },
        Destruction= {
            1,	--Shadow Bolt
            1,	--Immolate
            18,	--Searing Pain
            20,	--Rain of Fire
            30,	--Hellfire
            48,	--Soul Fire
            64,	--Incinerate
            75,	--Shadowflame
        },

        PalaHoly = {
            1, 	--Holy Light
            1,	--Seal of Righteousness
            8,	--Purify
            10,	--Lay on Hands
            12,	--Redemption
            14,	--Blessing of Wisdom
            20,	--Consecration
            20,	--Exorcism
            20,	--Flash of Light
            --	20,	--Sense Undead
            22,	--Concentration Aura
            24,	--Turn Evil
            30,	--Seal of Light
            14,	--Seal of Wisdom
            --	42,	--Cleanse
            50,	--Holy Wrath
            66,	--Divine Plea
            78,	--Sacred Shield
        },
        PalaProt = {
            1,	--Devotionaura
            6,	--Divine Protection
            8,	--Hammer of Justice
            --	19,	--Hand of Protection
            14,	--Righteous Defense
            --	16,	--Hand of Reckoning
            16,	--Righteous Fury
            --	18,	--Hand of Freedom
            --	20,	--Blessing of Kings
            --	22,	--Seal of Justice
            26,	--Hand of Salvation
            28,	--Shadow Resi Aura
            30,	--Divine Intervention
            32,	--Frost Resi Aura
            --	34,	--Divine Shield
            36,	--Fire Resi Aura
            46,	--Hand of Sacrifice
            75,	--Shield of Righteousness
        },
        Retri = {
            4,	--Blessing of Might
            4,	--Judgement of Light
            12,	--Jugment of Wisdom
            16,	--Retribution Aura
            28,	--Judgement of Justice
            44,	--Hammer of Wrath
            62,	--CrusaderAura
            64,	--Seal of Vengeance
            64,	--Seal of corruption
            70,	--Avenging Wrath
        },

    }
    SpellTable = {
        Arms = {
            2457,	--BattleStance
            78,		--Heroic Strike
            --100, 	--Charge
            772,	--Rend
            6343,	--Thunder Clap
            --1715,	--HarmString
            7384,	--Overpower
            694,	--Mocking Blow
            20230,	--Retaliation
            64382,	--Shattering throw
            57755,	--Heroic Throw
        },
        Furor = {

            6673,	--Battlesout
            34428,	--Victory Rush
            --1160,	--Demo Shout
            845,	--Cleave
            --5246,	--Intimidating Shout
            5308, 	--Execute
            1161,	--ChallengingShout
            2458,	--BeserkerStance
            12292,	--Death Wish
            20252,	--Intercept
            1464,	--Slam
            18499,	--Beserker rage
            1680,	--Whirlwind
            --6552,	--Pummel
            1719,	--Recklessness
            469,	--Commanding shout
            55694,	--Enraged Regeneration
        },
        Protection = {
            2687, 	--Bloodrage
            7386,	--Sunder Armor
            355,	--Taunt
            72,		--Shield Bash
            6572,	--Revenge
            2565,	--Shield Block
            676,	--Disarm
            12678,	--Stance Mastery
            871,	--ShieldWall
            23922,	--Shield Slam
            23920,	--Spell reflect
            3411,	--Intervene
        },

        Arcane = {
            1459,	--Arcane Intellect
            5504,	--Conjure Water
            587,	--Conjure Food
            5143,	--Arcane Missles
            --118,	--Polymorph
            604,	--Dampen Magic
            130,	--Slow Fall
            1449,	--Arcane Explosion
            1008,	--Amplify Magic
            475,	--Remove Curse
            --1953,	--Blink
            12051,	--Evocation
            1463,	--ManaShield
            --2139,	--CounterSpell
            759,	--Conjure Mana Gem
            6117,	--Mage Armor
            30451,	--Arcane Blast
            66,		--Invisibility
            43987,	--Ritual of Refreshment
            30449,	--Spellsteal
            55342,	--Mirror Image
        },
        Fire = {
            133,	--Fireball
            2136,	--Fire Blast
            2120,	--FlameStrike
            543,	--Fire Ward
            2948,	--Scorch
            30482,	--Molten Armor
            44614,	--Frostfire Bolt
        },
        FrostMage = {
            116,	--FrostBolt
            --122,	--Frost Nova
            10,		--Blizzard
            6143,	--Frost Ward
            120,	--Cone of Cold
            --7302,	--Ice Armor
            --45438,	--Ice Block
            30455,	--Ice Lance
        },


        Assasination = {
            2098,	--Eviscerate
            5171,	--Slice and Dice
            8647,	--Expose Armor
            --	703,	--Garrote
            --	8676,	--Ambush
            51722,	--Dismantle
            1943,	--Rupture
            --	1833,	--Cheap shot
            408,	--Kidney Shot
            --	32645,	--Evenom
            26679,	--Deadly Throw
        },
        Combat = {
            1752,	--Sinister Strike
            53,		--BackStab
            1776,	--Gouge
            --	5277,	--Evasion
            2983,	--Sprint
            --	1766,	--Kick
            1966,	--Feint
            5938,	--Shiv
            51723,	--Fan of Knives
        },
        Subletly = {
            --	1784,	--Stealth
            --	921,	--Pick Pocket
            --	6770,	--Sap
            14278,	--Ghostly Strike
            1725,	--Distract
            1856,	--Vanish
            2836,	--Detect Traps
            1842,	--Disarm Trap
            --	2094,	--Blind
            1860,	--Safe Fall
            31224,	--Cloak of Shadows
            57934,	--Tricks of the Trade
        },

        Balance = {
            5176,	--Wrath
            8921,	--Moonfire
            467,	--Thorns
            --	339, 	--Entangliing Roots
            16689,	--Natures Grasp
            770,	--Faerie Fire
            2637, 	--Hibernate
            2912,	--Starfire
            2908,	--Soothe Animal
            16914,	--Hurricane
            --	29166,	--Innervate
            --	22812,	--Barkskin
            33786,	--Cyclone
        },
        Feral = {
            5487,   --BearForm
            99,		--Demo Roar
            6795,   --growl
            6807,   --Maul
            5229,	--Enrage
            5211, 	--Bash
            --	1066,	--Aquatic Form
            779,	--Swipe[Bear]
            --	783,	--Travel Form
            16857,	--Faeri Fire Feral
            768,	--Cat Form
            1082,	--Claw
            --	5215,	--Prowl
            1079,	--Rip
            5221,	--Shred
            1822,	--Rake
            5217,	--Tigers Fury
            1850,	--Dash
            5209,	--Challenging Roar
            8998,	--Cower
            22568,	--Ferocious Bite
            6785,	--Ravage
            --	5225,	--Track Humanoids
            22842,	--Frenzied Regeneration
            9005,	--Pounce
            20719,	--Faelin Grace
            62600,	--Savage Defense
            --	33943,	--Flight Form
            22570,	--Maim
            33745,	--Lacerate
            62078,	--Swipe Cat
        },
        Restoration = {
            5185, 	--Healing Touch
            1126,	--Mark of the Wild
            774,	--Rejuvenation
            8936,	--Regrowth
            50769,	--Revive
            --	20484,	--Rebirth
            2782,	--Remove Curse
            2893,	--Abolish Poison
            740,	--Tranqility
            21849,	--Gift of the Wild
            33763,	--Lifebloom
            50464,	--Nourish
        },

        BeastMaster = {
            --	13163,	--Aspect of the Monkey
            13165,	--Aspect of the Hawk
            --	883,	--Call PET
            --	2641,	--Dismiss PET
            --	6991,	--Feed PET
            --	982,	--Revive PET
            --	1515,	--Tame Beast
            --	136,	--Mend PET
            --	6197,	--Eagle Eye
            --	1002,	--Eye of the Beast
            --	1513,	--Scare Beast
            --	5118,	--Aspect of the Cheetah
            34074,	--Aspect of the Vipper
            1462,	--Beast Lore
            13161,	--Aspect of the Beast
            --	13159,	--Aspect of the Pack
            20043,	--Aspect of the Wild
            34026,	--Kill Command
            61846,	--Aspect of the Dragonhawk
            53271,	--Masters Call
            --	62757,	--Call Stabled Pet

        },
        Marksman = {
            75,     --AutoShot
            1978,	--[Serpent Sting]
            3044,	--[Arcane Shot]
            --	1130,	--[Hunter's Mark]
            5116,	--[Concussive Shot]
            20736,	--[Distracting Shot]
            2643,	--[Multi-Shot]
            3043,	--[Scorpid Sting]
            3045,	--[Rapid Fire]
            --	1543,	--[Flare]
            3034,	--[Viper Sting]
            1510,	--[Volley]
            56641,	--[Steady Shot]
            19801,	--[Tranquilizing Shot]
            53351,	--[Kill Shot]
        },
        Survival = {
            2973,   --Raptor strike
            --	1494,	--Track Beasts]
            --	19883,	--Track Humanoids]
            2974,	--Wing Clip]
            13795,	--Immolation Trap]
            1495,	--Mongoose Bite]
            --	19884,	--Track Undead]
            781	,	--Disengage]
            1499,	--Freezing Trap]
            --	19885,	--Track Hidden]
            --	19880,	--Track Elementals]
            13809,	--Frost Trap]
            5384,	--Feign Death]
            --	19878,	--Track Demons]
            13813,	--Explosive Trap]
            --	19882,	--Track Giants]
            --	19879,	--Track Dragonkin]
            19263,	--Deterrence]
            34600,	--Snake Trap
            34477,	--Misdirection]
            60192,	--Freezing Arrow]
        },

        Elemental = {

            403,	--Lightning Bolt
            8042,	--Earth Shock
            --	2484,	--Earthbind Totem
            5730,	--Stoneclaw Totem
            8050,	--Fame Shock
            3599,	--Searing Totem
            1535,	--Fire Nova
            --	370,	--Purge
            --	57994,	--Wind Shear
            --	8056,	--Frost Shock
            8190,	--Magma Totem
            66842,	--Call of the Elements
            421, 	--Chain Lightning
            66843,	--Call of the Ancestors
            66844,	--Call of the Spirits
            2894,	--Fire Ele Totem
            51505,	--Lava Burst
            51514,	--Hex

        },
        Enhancement = {
            8017, 	--Rockbiter
            8071,	--StoneSkin Totem
            324,	--Lightning Shield
            8024,	--Flametongue Wpn
            8075,	--Strenght of Earth Totem
            2645,	--Ghost Wolf
            8033,	--Frostbrand Wpn
            131,	--Water Breathing
            8181,	--Frost Resistance totem
            --	6196,	--Far Sight
            8184,	--Fire Resistance Totem
            8227,	--Flametongue Totem
            546,	--Water Walking
            556,	--Astral Recall
            --	8177,	--Grounding Totem
            10595,	--Nature Resi Totem
            --	8242,	--Windfury Wpn
            8512,	--Windfury Totem
            6495,	--Sentry Totem
            3738,	--Wrath of the Air Totem
            2062,	--Earth Ele Totem
            2825,	--Bloodlust
            32182,	--Heroism
        },
        ShamanResto= {
            331,	--Healing Wave
            2008,	--Ancestral Spirit
            526,	--Cure Toxins
            8134,	--Tremor Totem
            5394,	--Healing Stream Totem
            8004,	--Lesser Healing Wave
            52127,	--Water Shield
            --	5675,	--Mana Spring Totem
            51730,	--Earthliving Wpn
            --	20608,	--Reincarnation
            36936,	--Totemic Recall
            --	8170, 	--Cleansing Totem
            1064,	--Chain Heal

        },

        Disci = {
            1243,	--Power Word Fort
            17,		--PowerWord Shield
            --	588,	--Inner Fire
            --	527,	--Dispel Magic
            --	6346,	--Fear Ward
            9484,	--Shacke Undead
            8129,	--Mana Burn
            14752,	--Divine Spirit
            1706,	--Levitate,
            32375,	--Mass Dispel

        },
        PriestHoly = {
            139,	--Renew
            2006,	--Ressurection
            528,	--Cure Disease
            2054,	--Heal
            2061,	--Flash Heal
            --	14914,	--Holy Fire
            15237,	--Holy Nova
            596,	--Prayer of Healing
            552,	--Abolish Disease
            2060,	--Greater Heal
            32546,	--Binding Heal
            33076,	--Prayer of Mending
            64843,	--Divine Hymn
            64901,	--Hymn of Hope
        },
        Shadow = {
            589, 	--Shadow Word Pain
            586,	--Fade
            8092,	--Mind Blast
            --	8122,	--Psychic Scream
            2944,	--Devo Plague
            453,	--Mind Soothe
            2096,	--Mind Vision
            605,	--Mind Control
            976,	--ShadowProtection
            32379,	--Shadow word Death
            34433,	--Shadowfiend
            48045,	--Mind Sear
        },

        Affliction = {
            172,	--Corruption
            702,	--Curse of Weakness
            --	1454,	--Life Tap
            --	980,	--Curse of Agony
            --	5782,	--Fear
            1120,	--Drain Soul
            689,	--Drain Life
            5138,	--Drain Mana
            1714,	--Curse of Tongues
            --	1490,	--Curse of the Elements
            5484,	--Howl of Terror
            --	6789,	--Death Coil
            603,	--Curse of Doom
            27243,	--Seed of Corruption
        },
        Demonology = {
            --	687,	--Demon Skin
            --	688,	--Summon Imp
            6201, 	--Create Healthstone
            755,	--Health Funnel
            5697,	--Unending Breath
            693,	--Create Soulstone
            698,	--Eye of Kilrogg
            5500,	--Sense Demons
            132,	--Detect invis
            --	710,	--Banish
            6366,	--Create Firestone
            1098,	--Enslave Demon
            6229,	--Shadow Ward
            2362,	--Create SpellStone
            28176,	--Fel Armor
            29858,	--Soulshatter
            29893,	--Ritual of Soulshatter
            48018,	--Demonic Circle Summon
            48020,	--Demonic Circle Teleport
            -- 1122 --inderno
        },
        Destruction= {
            686,	--Shadow Bolt
            348,	--Immolate
            5676,	--Searing Pain
            5740,	--Rain of Fire
            1949,	--Hellfire
            6353,	--Soul Fire
            29722,	--Incinerate
            47897,	--Shadowflame
        },

        PalaHoly = {
            635, 	--Holy Light
            21084,	--Seal of Righteousness
            1152,	--Purify
            633,	--Lay on Hands
            7328,	--Redemption
            19742,	--Blessing of Wisdom
            26573,	--Consecration
            879,	--Exorcism
            19750,	--Flash of Light
            --	5502,	--Sense Undead
            19746,	--Concentration Aura
            10326,	--Turn Evil
            20165,	--Seal of Light
            19742,	--Seal of Wisdom
            --	4987,	--Cleanse
            2812,	--Holy Wrath
            54428,	--Divine Plea
            53601,	--Sacred Shield
        },
        PalaProt = {
            465,	--Devotionaura
            498,	--Divine Protection
            853,	--Hammer of Justice
            --	1022,	--Hand of Protection
            31789,	--Righteous Defense
            --	62124,	--Hand of Reckoning
            25780,	--Righteous Fury
            --	1044,	--Hand of Freedom
            --	20217,	--Blessing of Kings
            --	20164,	--Seal of Justice
            1038,	--Hand of Salvation
            19876,	--Shadow Resi Aura
            19752,	--Divine Intervention
            19888,	--Frost Resi Aura
            --	642,	--Divine Shield
            19891,	--Fire Resi Aura
            6940,	--Hand of Sacrifice
            53600,	--Shield of Righteousness
        },
        Retri = {
            19740,	--Blessing of Might
            20271,	--Judgement of Light
            53408,	--Jugment of Wisdom
            7294,	--Retribution Aura
            53407,	--Judgement of Justice
            24275,	--Hammer of Wrath
            32223,	--CrusaderAura
            32801,	--Seal of Vengeance
            53736,	--Seal of corruption
            31884,	--Avenging Wrath
        },

    }
    TalentSpecTable ={
        "Arms",
        "Furor",
        "Protection",
        "Arcane",
        "Fire",
        "FrostMage",
        "Assasination",
        "Combat",
        "Subletly",
        "Balance",
        "Feral",
        "Restoration",
        "BeastMaster",
        "Marksman",
        "Survival",
        "Elemental",
        "Enhancement",
        "ShamanResto",
        "Disci",
        "PriestHoly",
        "Shadow",
        "Affliction",
        "Demonology",
        "Destruction",
        "PalaHoly",
        "PalaProt",
        "Retri"

    }
    SpellRacials = {
        Active = {
            59752, -- Every Man for himself (human)
            59542, --[Gift of the Naaru] AP and SP Dreanei
            7744,  --[Will of the Forsaken] Undead
            20549, --[War Stomp]
            20572, --[Blood Fury] AP
            33702, --[Blood Fury] SP
            20577, --[Cannibalize]
            20589, --[Escape Artist]
            20594, --[Stoneform]
            25046, --[Arcane Torrent] ENERGY
            26297, --[Berserking] Troll
            28730, --[Arcane Torrent] MANA
            58984, --[Shadowmeld]
        },
        Passive ={
            -- 822,    --[Magic Resistance] bloodelf
            5227,   --[Underwater Breathing]
            6562,   --[Heroic Presence]
            20550,  --[Endurance]
            20551,  --[Nature Resistance]
            20579,  --[Shadow Resistance]
            20592,  --[Arcane Resistance]
            20596,  --[Frost Resistance]
            20555,  --[Regeneration]
            20557,  --[Beast Slaying]
            20573,  --[Hardiness]
            20574,  --[Axe Specialization]
            21563,  --Command
            20591,  --[Expansive Mind]
            20598,  --[The Human Spirit]
            20595,  --[Gun Specialization]
            20597,  --[Sword Specialization]
            20599,  --[Diplomacy]
            20864,  --[Mace Specialization]
            21009,  --[Elusiveness]
            58943,  --[Da Voodoo Shuffle]
            58985,  --[Perception]

        }

    }
    local MyHandlers = AIO.AddHandlers("SuperTalents", {SUPERLearnSpell,SUPERUNLearnSpell,superenchant})


    function MyHandlers.SUPERLearnSpell(player, p1, p2)
        print("learning spell"..p1.." p2: "..p2)
        local id = SpellTable[p1][p2];
        if (id)then
            if(SpellLevelTable[p1][p2] <= player:GetLevel())then
                print("learning spell".. id)
                player:LearnSpell(id,false)
            end
        end
    end

    function MyHandlers.SUPERUNLearnSpell(player, p1,p2)
        local id = SpellTable[p1][p2];
        if (id)then
            if(player:HasSpell(id) == true)then
                print("YO")
                player:UnLearnSpell(id,false)
            end
        end
    end

    function MyHandlers.superenchant(player,enchant,slot)
        local i = 1;
        local  item = nil;
        while item == nil do
            item= player:GetItemByPos( 255, i );
            i = i + 1;
        end
        print(item:GetName())
        if(slot == 1)then
            print(item:SetEnchantment(enchant,9));
        end
        if(slot == 2)then
            print(item:SetEnchantment(enchant,10));
        end
        if(slot == 3)then
            print(item:SetEnchantment(enchant,11));
        end
        if(slot < 0)then
            print(item:SetEnchantment(enchant,slot*-1));
        end
    end

else
    -- we are on client
    print("Supyall")
    function AIO_LearnSpell(p1,p2)
        print("sending Learn "..tostring(Nog_Selected_Spell.info.name))
        AIO.Handle("SuperTalents", "SUPERLearnSpell",p1,p2)
    end


    function AIO_UnLearnSpell(p1,p2)
        print("sending Unlearn "..Nog_Learn_Selected_Spell.info.name)
        AIO.Handle("SuperTalents", "SUPERUNLearnSpell",p1,p2)
    end
    function AIO_SetEnchant(enchant,item)
       -- print("sending Unlearn "..Nog_Learn_Selected_Spell.info.name)
        AIO.Handle("SuperTalents", "superenchant",enchant,item)
    end
end


print("yo")


    